최원유 2주차 과제 제출하겠습니다!
sosow0212/2024-mju-mentoring pull request #10
Opened 2024-01-26 18:23 UTC by ChoiWonYu

이번 미션을 진행하면서 많은 고민과 어려움이 있었습니다.

첫 번째로 엔티티 객체를 객체지향적으로 바꾸면서 값 타입으로 바꾸는 작업을 하면서 VO와 동일하다고 생각했습니다. 때문에 불변성을 유지해야 한다고 생각했고, update 로직을 VO의 값을 수정하는 것이 아닌 새로운 VO를 생성해서 교체하는 로직으로 수정했습니다. 제가 잘못 생각한 것이라면 피드백 부탁드리겠습니다.

두 번째로 현준님의 슬랙에서 하신 질문과 답변을 보고, 테스트의 격리에 대해 공부해봤습니다.
말씀해주신 JdbcTemplate 대신 EntityManager를 사용했는데 스프링을 테스트 해본 경험이 없다보니 맞게 했는지에 대한 정확한 판단이 서지 않았습니다..

마지막으로 나머지 테스트 코드 작성을 하면서 제가 많이 부족하다는 것을 알게 되었습니다.. 부족하다고 생각하는 부분들과 리뷰 해주시는 부분들 모두 열심히 공부해보겠습니다..!

2024-01-27 05:42 UTC, sosow0212 requested changes
수고하셨습니다!
공부 많이하신게 진짜 많이 느껴집니다 👍

코드는 크게 문제가 없어보입니다.
몇 가지 얘기 나눠보고 싶은데 질문에 대해 답변 부탁드립니다 ㅎㅎ

2024-01-27 05:42 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/application/dto/BoardCreateRequest.java
> +public record BoardCreateRequest(String title, String content) {
record 👍
자바17에서 제공하는 또 다른 기능들도 확인해보면 좋을 것 같습니다!

2024-01-27 05:42 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/domain/Board.java
>      }
요 부분도 롬복으로 뺄 수 있을 것 같네요 ㅎㅎ
`@NoArgs~~ (access = ... PROTECTED)`

2024-01-27 05:42 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/domain/Board.java
> +    }
이 부분만 따로 사용할 일이 있을까요?
밑에 getTitle() 이런 메서드가 있어서 리뷰 남겨요 ㅎㅎ

`디미터의 법칙` 검색하셔서 확인해보시면 좋을 것 같습니다.

2024-01-27 05:42 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/domain/Description.java
> +    private String content;
@Column을 달아서 nullable 과 같은 속성을 추가해보면 좋을 것 같습니다

추가적으로 @Lob은 무엇인지도 확인해보세요!

2024-01-27 05:42 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/domain/Board.java
> +        this.description = Description.of(title, content);
캬 update로직이 아닌 새로 생성해서 만들어주는거 좋네요. 
저도 습관적으로 `this.description.update()` 이런 식으로 사용하곤 하는데 하는데 pr내용에 남겨주신 것처럼 저도 불변을 유지하기 위해서 새로운 객체로 교체하는게 더 좋다고 생각합니다.
저도 하나 배우고 가네요 👍

2024-01-27 05:42 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/exception/exceptions/BoardNotFoundException.java
> +
불필요한 공백이 있습니다!

2024-01-27 05:42 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/exception/exceptions/BoardNotFoundException.java
> +        super("해당 게시물을 찾을 수 없습니다");
예전에 제가 우테코에서 리뷰 받은 내용이 생각나네요!
이거는 그냥 참고만 하고 선택하시면 됩니다!

매개변수로 id 값을 넣어주면 프론트엔드 개발자 입장에선 어떤 부분이 문제인지 디버깅하기 용이하다고 합니다.
예를 들어 프론트엔드 개발자는 1번 게시글이 존재하고 그 값을 보냈는데 게시글을 찾을 수 없다는 에러만 나기보다는 3번 게시글을 찾을 수 없다고 예외가 날아오면 실수로 3번을 보내는 것을 확인할 수 있는 것처럼 협업할 때는 이런 부분을 얘기하면서 적절하게 선택하는 것도 좋을 것 같습니다 ㅎㅎ

2024-01-27 05:42 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/infrastructure/BoardJpaRepository.java
> +    void deleteById(final Long id);
1. JPA에서 밑에 상황에선 deleteById는 어떤 쿼리가 나갈까요?
답변과 왜 그렇게 나오는지 공유 부탁드립니다!

```
// 1번 게시글은 존재하는 상황

public void deleteById(final Long id) {
     jpaRepository.deleteBy(1);
}
```


2. 1~n개의 게시글 id가 담긴 `List<Long> deletedId` 가 넘어왔을 때 어떻게 제거해줘야지 적은 쿼리로 효율적으로 지울 수 있을까요? 여러가지 방식이랑 더불어 상세하게 답변 부탁드립니다!

2024-01-27 05:42 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/domain/Member.java
> +    AuthInformation authInformation;
접근 제어자가 빠진 이유가 있을까요!?

2024-01-27 05:42 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/application/BoardServiceTest.java
> +                .isEqualTo(1);
ast(findBoards).hasSize(1) 로 바꿀 수 있습니다 ㅎㅎ

2024-01-27 05:42 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/application/BoardServiceTest.java
> +                .ignoringFields("id")
👍

2024-01-27 05:42 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/application/BoardServiceTest.java
> +    }
update 메서드에 대한 테스트는 없나요?!
해당 경우의 예외까지 모두 테스트 작성 부탁드릴게요!

2024-01-27 05:42 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/fixture/BoardFixture.java
> +    private static final Long DEFAULT_ID = 1L;
픽스쳐에서까지 매직넘버 상수화 습관이 들었나보네요 ㅋㅋㅋㅋㅋ 좋은 습관인 것 같아요 👍

2024-01-27 05:42 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +@ActiveProfiles("test")
해당 어노테이션은 무슨 역할을 하나요?

2024-01-27 05:42 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
1. RANDOM_PORT를 사용하는 이유는 무엇인가요?
2. @SpringBootTest를 사용하면 안되나요? 차이점은 무엇일까요!

2024-01-27 05:42 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +        cleaner.execute();
진짜 학습이 빠르네요 👍

1. 어노테이션을 이용해서 테스트 격리하는 방법
2. extends를 이용해서 테스트를 격리하는 방법

이 두 가지도 고민해보면 좋을 것 같습니다.
현재는 테스트 격리가 필요한 상황마다 @BeforeEach 코드가 중복될 것 같습니다!

2024-01-27 05:42 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +    void 게시글_저장_테스트() {
이건 팁 아닌 팁인데요 쿼리가 생각보다 잘못나가는 경우가 많습니다.
쿼리 개선을 한다면 서버에서 더 많은 양을 처리할 수 있기 때문에 정말 중요하다고 생각합니다.

해당 계층을 테스트할 때 검증도 좋지만 쿼리가 의도한대로 나가는지 한 번씩 디버깅해보는 것도 좋을 것 같습니다.
yml에서 쿼리볼 수 있도록 설정하면 확인 가능합니다!

2024-01-27 05:42 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +        assertThat(savedBoard.getId()).isEqualTo(1L);
usingRecursive~() 사용해보면 좋을 것 같아요!

2024-01-27 05:42 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +        List<Board> findBoards = boardJpaRepository.findAll();
해당 부분은 then으로 가는게 적절하다고 생각합니다!

2024-01-27 05:42 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +        assertThat(findBoards.isEmpty()).isTrue();
`ast(findBoards).isEmpty()` 아마 요것도 되지 않을까요??

2024-01-27 05:42 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/ui/BoardControllerWebMvcTest.java
> +    @MockBean
MockBean을 캐싱하는 방법이 있을까요?

해당 글을 읽어보면 도움이 될 것 같습니다~

[링크1](https://docs.spring.io/spring-framework/reference/testing/testcontext-framework/ctx-management/caching.html)

[링크2](https://docs.spring.io/spring-framework/reference/testing/testcontext-framework/ctx-management/caching.html)

2024-01-27 05:42 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/ui/BoardControllerWebMvcTest.java
> +        mockMvc.perform(post("/boards")
나중에 해당 클래스에서 문서화도 진행할 수 있습니다!
REST Docs도 이왕 공부해보면 좋을 것 같습니다

2024-01-27 05:42 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/global/DatabaseCleaner.java
> +public class DatabaseCleaner implements InitializingBean {
진짜 나이스하네요

2024-01-27 06:04 UTC, eom-tae-in requested changes
고생하셨습니다!   수정해 주세요~

2024-01-27 06:04 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/board/domain/Board.java
>      protected Board() {
@Lombok으로 생성자를 처리하는 방식과 실제 코드로 작성하는 방식이 공존합니다. 하나로 통일해주시면 좋을거 같아요!

2024-01-27 06:04 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/board/exception/exceptions/BoardNotFoundException.java
> +
개행 삭제해주세요~

2024-01-27 06:04 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/member/domain/AuthInformation.java
> +    String username;
개행과 private 접근 제어자 붙여주세요!

2024-01-27 06:04 UTC, eom-tae-in commented on src/test/java/com/mju/mentoring/board/domain/BoardTest.java
> +        board.update("업데이트 제목", "업데이트 내용");
"업데이트 제목" 과 "업데이트 내용"을 given 절에서 주는 건 어떨까요?

2024-01-27 06:04 UTC, eom-tae-in commented on src/test/java/com/mju/mentoring/board/domain/BoardTest.java
> +        assertNotEquals(origin, board.getDescription());
현재 값이 틀린지 검증하는 방식인데 값이 맞는지 검증하는 방식으로 바꾸는 건 어떨까요?

2024-01-27 06:04 UTC, eom-tae-in commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +@ActiveProfiles("test")
- @ActiveProfiles("test")를 붙인 이유가 무엇인가요??
- @SpringBootTest 대신 @DataJpaTest를 이용해 테스트하는 것은 어떨까요?

2024-01-31 16:15 UTC, ChoiWonYu commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +@ActiveProfiles("test")
자동으로 임베디드 DB가 사용되는 건지 몰랐습니다..! 수정하겠습니다!

2024-02-06 02:55 UTC, eom-tae-in requested changes
고생하셨습니다. 몇가지만 수정해주세요

2024-02-06 02:55 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/member/application/auth/AuthService.java
> +        }
이 부분도 checkDuplicate처럼 메서드 분리를 해주면 좋을거 같아요

2024-02-06 02:55 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/member/application/auth/AuthService.java
> +import com.mju.mentoring.member.ui.auth.dto.TokenResponse;
서비스 계층에서 상위 계층을 참조하고 있네요
singIn 메서드에서 TokenResponse를 반환하지 않고 accessToken을 바로 반환해줘서 상위 계층 참조를 하지 않도록 하는게 좋아보여요!

2024-02-06 02:55 UTC, eom-tae-in commented on src/test/java/com/mju/mentoring/member/application/auth/AuthServiceTest.java
> +    void 회원가입_테스트() {
테스트 메서드의 관심사가 비슷한 것들을 @Nested 클래스로 묶어도 괜찮을거 같아요

2024-02-06 11:56 UTC, sosow0212 approved these changes
계층 구조도 많이 이해했고, 테스트도 잘하셔서 일단 여기서 어프루브 하겠습니다!
그래도 아직은 살짝 개선할 점이 보이는데 pr 범위가 길어져서 일단 여기서 끊고 다음 미션부터 개선해나가면 좋을 것 같습니다!

수고하셨습니다 👍

2024-02-06 11:56 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/domain/TokenManager.java
> +package com.mju.mentoring.member.domain;
TokenManager는 외부 라이브러리를 사용하고 있는데 현재 domain안에 있습니다.
그렇다면 도메인이 외부 라이브러리에 의존적인 것일까요?

domain안에는 순수 interface를 두고, infrastructure 계층에 TokenManagerImpl로 JWT와 같은 외부 라이브러리를 사용하는 구현체들을 두면 좋을 것 같습니다.

이렇게 했을 때 유지보수와 테스트, 리팩토링 관점에서 어떤 장점으로 올까요??

2024-02-06 11:56 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/ui/BoardAcceptanceTestFixture.java
> +public class BoardAcceptanceTestFixture extends BaseAcceptanceTest {
와.. 어려웠을텐데 잘 하셨네요 👍

2024-02-06 11:57 UTC, merged