Zoid79
sosow0212/2024-mju-mentoring pull request #11
Opened 2024-02-03 16:51 UTC by zoid79

member의 구조를 id 와 member description을 추가하였고 그 안에는 로그인 할 때 사용하는 memberId와 username, password, nickname가 있습니다.
그 중 memberId와 username은 유니크하게 설정하였습니다
테스트 코드 전부 추가하였고 어떤 레이어에 추가해야할지 몰라 일단 provider디렉토리 생성 후 그 안에 JwtTokenProvider 추가하였습니다.
테스트 코드 레이어별 작성하였습니다

2024-02-04 07:28 UTC, sosow0212 requested changes
몇 부분만 수정해주세요~ 작업하시느라 수고하셨습니다.
그리고 저번 리뷰부터 컨벤션이 자꾸 맞지 않는데 컨벤션 부분 설정이랑 확인 한 번씩 더 부탁드립니다

2024-02-04 07:28 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/controller/MemberController.java
> +    @Autowired
1. 개행 추가해주세요
2. @Required~를 쓰셨는데 Autowired를 사용하신 이유는 무엇인가요? + 생성자 주입과 필드 주입의 차이가 무엇일까요

2024-02-04 07:28 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/controller/MemberController.java
> +        System.out.println(loginRequest.password());
System.out 출력과 log의 차이는 무엇일까요?

2024-02-04 07:28 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/domain/Member.java
> +    }
1. 구글 컨벤션 따르면 { return true } 이렇게 중괄호를 써주는게 좋습니다.
2. 그리고 지금 memberDescription에서 password를 꺼내와서 밖에서 비교를 해주는데 이러면 캡슐화가 깨지는 것 아닌가요?
3. 메서드 네이밍은 동사로 시작해야하고 지금은 너무 추상적인 네이밍인데 어떤 검증인지 명시해주세요

2024-02-04 07:28 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/domain/MemberDescription.java
> +    @Column(nullable = false,unique=true,name = "member_Id")
정렬이 안 되어 있습니다

2024-02-04 07:28 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/provider/JwtTokenProvider.java
> +@Component
Component를 통해 빈을 등록해주었는데요. 빈을 등록한 이유가 무엇인가요? 빈은 언제 등록해야할까요?

2024-02-04 07:28 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/provider/JwtTokenProvider.java
> +    }
1. `int i`는 무엇인가요?
2. withoutSignature에서 Signature은 어떤 것을 의미하나요?
3. temp는 무엇인가요? 클린코드 입각해서 네이밍 신경 써주세요!
4. 정렬이 안되어 있습니다.

2024-02-04 07:28 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/service/MemberService.java
> +    @Transactional(readOnly = true)
둘 사이에 개행이 비어있네요

2024-02-04 07:28 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/service/MemberService.java
> +
불필요한 공백

2024-02-04 07:28 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/service/MemberService.java
> +            throw new NoMemberException("비밀번호가 일치하지 않습니다");
여기도 { } 가 빠져있네요
그리고 NoMemberException은 무엇인가요? 네이밍으로 어떤 클래스인지 추측을 전혀 할 수 없습니다. 이러면 협업에서 문제가 많이 생길 수 있기 때문에 신경써주세요.

2024-02-04 07:28 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/service/MemberService.java
> +        return memberRepository.findByMemberId(memberId).orElseThrow(() -> new NoMemberException("id가 일치하지 않습니다"));
객체지향 생활체조 4번 참고해주세요

2024-02-04 07:28 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/controller/MemberController.java
> +    @PostMapping("/login")
회원 가입은 없나요?

2024-02-04 07:28 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/domain/MemberDescriptionTest.java
> +            softly.assertThat(member.validation(rightpassword)).isEqualTo(true);
().isTrue()
().isFalse() 이렇게 검증해도 됩니다!

2024-02-04 07:28 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/infrastructure/MemberFakeRepository.java
> +import java.util.*;
import 와일드카드

2024-02-04 07:28 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/infrastructure/MemberFakeRepository.java
> +                .map(map::get);
map::get으로 주면 Optional로 반환이 되나요? 없다면 예외가 발생할 것 같은데 그러면 프로덕션 코드 테스트 때 문제가 생기지 않을까요?

2024-02-04 07:28 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/infrastructure/MemberFakeRepository.java
> +        return Optional.ofNullable(mapForId.get(memberId));
이것도 위에 리뷰와 비슷하게 문제 생기지 않을까요?

2024-02-04 07:28 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/service/MemberServiceTest.java
> +        memberService = new MemberService(memberRepository,new JwtTokenProvider());
JwtTokenProvider는 빈인데 저렇게 등록하고 테스트를 해도 될까요?

2024-02-04 07:28 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/service/MemberServiceTest.java
> +            assertEquals("user1", jwtClaims.getBody().get("user_id", String.class));
1. 지금 토큰을 반환하고 결과에서 새로운 jwt토큰 객체를 만들고 거기에 덮어씌운 후에 결과를 검증하는데 이렇게 하면 신뢰성에 문제가 있어보입니다.
2. 다중 검증은 softly 사용해주세요

2024-02-04 08:17 UTC, eom-tae-in requested changes
고생하셨습니다. 몇가지만 수정해주세요:)

2024-02-04 08:17 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/exam/board/provider/JwtTokenProvider.java
> +        Claims claims = Jwts.claims().setSubject("access_token");
한 줄에 체이닝은 한개만 사용해주세요! (객체지향 생활 체조 원칙 4번)

2024-02-04 08:17 UTC, eom-tae-in commented on src/test/java/com/mju/mentoring/board/infrastructure/MemberFakeRepository.java
> +    public Optional<Member> findByMemberId(String memberId) {
매개변수에 일관성 있게 final 키워드를 사용하거나 사용하지 않도록 수정해주세요~

2024-02-04 08:17 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/exam/board/domain/Member.java
> +    }
+ boolean 타입을 반환하는 메서드의 이름은 보통 is/can/has 로 시작하게 작성합니다.
해당 메서드의 네이밍으로는 validation보다 isValidPassword와 같은 네이밍이 좀 더 적절해 보이네요:)

2024-02-05 15:26 UTC, zoid79 commented on src/test/java/com/mju/mentoring/board/infrastructure/MemberFakeRepository.java
> +    public Optional<Member> findByMemberId(String memberId) {
수정하였습니다

2024-02-05 15:26 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/provider/JwtTokenProvider.java
> +        Claims claims = Jwts.claims().setSubject("access_token");
수정하였습니

2024-02-05 15:26 UTC, zoid79 commented on src/test/java/com/mju/mentoring/board/service/MemberServiceTest.java
> +            assertEquals("user1", jwtClaims.getBody().get("user_id", String.class));
softly로 변경하였습니다
1번의 경우 무슨 이야기인지 이해 못하였으나 제 방식은 getLoginToken으로 token 생성후 parser와 SECRET 키를 사용, 다시 파싱하여서 데이터가 그대로인지 확인하는 방식으로 작성하였습니다

2024-02-05 15:26 UTC, zoid79 commented on src/test/java/com/mju/mentoring/board/service/MemberServiceTest.java
> +        memberService = new MemberService(memberRepository,new JwtTokenProvider());
테스트는 통과하였으나 어떤게 나은 방법인지 몰라 일단 다른 방법으로 변경하였습니다
수정하였습니다

2024-02-05 15:26 UTC, zoid79 commented on src/test/java/com/mju/mentoring/board/infrastructure/MemberFakeRepository.java
> +        return Optional.ofNullable(mapForId.get(memberId));
위와 마찬가지로 optional로 반환은 되지만 테스트 코드에서 exception이 발생하지 않도록 
		assertThat(foundBoard).isNotEmpty();
를 추가하였습니

2024-02-05 15:26 UTC, zoid79 commented on src/test/java/com/mju/mentoring/board/infrastructure/MemberFakeRepository.java
> +                .map(map::get);
확인 해 보았는데 optional로 반환이 됩니다

2024-02-05 15:26 UTC, zoid79 commented on src/test/java/com/mju/mentoring/board/infrastructure/MemberFakeRepository.java
> +import java.util.*;
수정하였습니다

2024-02-05 15:26 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/provider/JwtTokenProvider.java
> +@Component
Memberservice 안에서 토큰 관리까지 하면 너무 커질 것 같아 jwt token provider을 분리하였고 memberservice 안에서 생성자 없이 사용하려고 하였습니다.
빈을 언제 등록해야 할 지에 대해서는 찾아보았는데 아직 배움이 부족한 것 같아 정확한 답을 내지 못하겠네요
이후 더 찾아보도록 하겠습니다

2024-02-05 15:26 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/domain/MemberDescription.java
> +    @Column(nullable = false,unique=true,name = "member_Id")
수정하였습니다

2024-02-05 15:26 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/domain/Member.java
> +    }
네이밍 변경과 중괄호 추라하였고 MemberDescription 안에서 validation이 일어나게 변경하였습니다

2024-02-05 15:26 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/controller/MemberController.java
> +        System.out.println(loginRequest.password());
System.out 은 한번 출력되면 휘발되는 단순 출력이고 log는 휘발시키지 않을 수 있으며 위험 레벨 등 부가정보까지 확인할 수 있습니다.

2024-02-05 15:27 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/controller/MemberController.java
> +    @Autowired
1. 개행 추가하였습니다
2. 아무 생각없이 두가지 다 사용한 것 같습니다 Autowried 삭제 하였습니다.
검색하여보았는데 생성자 주입은 빈을 생성하는 과정에서 di를 수행하고 필드 주입은 먼저 빈을 생성 하고 그 안에 있는 필드에 di하는 것으로 이해했습니다. 순환 참조 등 혹시 모를 에러에 대비하려면 전자의 경우가 낫다는 검색 결과를 얻었습니다

2024-02-05 15:40 UTC, zoid79 commented on src/test/java/com/mju/mentoring/board/domain/MemberDescriptionTest.java
> +            softly.assertThat(member.validation(rightpassword)).isEqualTo(true);
감사합니다! 수정하였습니다

2024-02-05 15:40 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/controller/MemberController.java
> +    @PostMapping("/login")
로그인만 있었던 것 같아서 그것만 작성하긴 했습니다

2024-02-05 15:40 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/service/MemberService.java
> +        return memberRepository.findByMemberId(memberId).orElseThrow(() -> new NoMemberException("id가 일치하지 않습니다"));
수정하였습니다

2024-02-05 15:40 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/service/MemberService.java
> +            throw new NoMemberException("비밀번호가 일치하지 않습니다");
MemberNotFoundException 수정하였습니다

2024-02-05 15:40 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/service/MemberService.java
> +
수정하였습니다

2024-02-05 15:40 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/service/MemberService.java
> +    @Transactional(readOnly = true)
수정하였습니다

2024-02-05 15:40 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/provider/JwtTokenProvider.java
> +    }
수정하였습니

2024-02-06 09:31 UTC, eom-tae-in approved these changes

2024-02-06 11:40 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/provider/JwtTokenProvider.java
> +@Component
좋습니다 이런 건 고민 한 번쯤 해보면 좋을 것 같아서 말씀 드린 리뷰였습니다!

2024-02-06 11:41 UTC, sosow0212 approved these changes
수고하셨습니다! 일단 pr이 쌓여서 한 번 끊고 가겠습니다.
다음 미션부터 리팩토링 하면서 개선해보면 좋을 것 같습니다.

2024-02-06 11:41 UTC, merged