김남훈 4주차 과제 제출합니다
sosow0212/2024-mju-mentoring pull request #12
Opened 2024-02-12 09:14 UTC by zoid79

어노테이션 부분은 코드 제가 짠 코드 바깥쪽에서 동작하는 것이라서 맞는 어떠한 원리로 작동하는지를 아는 것이 어려웠습니다

save메소드를 실행시킬 때 memberId의 값에 따라 service에서 오버로딩을 사용하여 다른 메소드를 호출하게 하였습니다.
하지만 찾아보니 어노테이션인터페이스에서 다른 메소드를 controller에서 호출할 수도 있어 어떤 방식이 나은 방식인지는 모르겠습니다
또한 memberId만 받다 보니 member 객체를 repository에서 받아와야 하는데 boardService 안에서 memberRepository와 boardRepository가 함께 있는게 맞지 잘 모르겠습니다
하지만 다른 방식이 떠오르지 않아서 이렇게 작성하였습니다

오버로딩때문에 생긴 메소드 service 레이어에서 테스트 코드 작성하였습니다

2024-02-13 02:30 UTC, sosow0212 requested changes
작업하시느라 수고하셨습니다 👏
코드가 많이 깔끔해졌네요! 리뷰 반영하고 다시 제출해주세요~
헷갈리거나 질문할 내용 있으시면 언제든 DM 보내주세요!

2024-02-13 02:30 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/component/AuthAccountResolver.java
> +		if (httpServletRequest != null) {
지금 if문을 3중첩으로 사용하고 있는데요
해당 구조로 했을 때 다음과 같은 문제점이 생깁니다.

1. 가독성 저해
- 각 분기마다 어떤 것을 위해서 사용하는지 알기 힘듭니다.

2. 예외처리 부재
- if문을 타지 않는 경우 즉 -1L을 반환하는 경우는 예외 상황이 될 텐데요 (토큰 정보가 없어서 -1을 주게 되므로) 이때는 정상적인 API 호출이 불가능합니다. 따라서 -1을 주기보다 예외를 주는 것이 적절해 보입니다.

차라리 처음에 if(servlet~ == null) { throw ... } 로 분기를 하나 줄여주고
그 후에 필요한 분기들의 조건문도 메서드 분리를 통해 어떤 분기인지 뜻을 주는게 좋아보입니다

2024-02-13 02:30 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/component/AuthAccountResolver.java
> +		if (httpServletRequest != null) {
그리고 가급적이면 상수처리를 해줘서 관리와 가독성을 용이하게 해주세요!

2024-02-13 02:30 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/component/JwtTokenProvider.java
> +	private static final long ACCESS_EXPIRED_TIME = 1000 * 60 * 30;            // 30분
이 부분도 yml에서 값을 주입 받도록 해주는 건 어떨까요?

2024-02-13 02:30 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/component/JwtTokenProvider.java
> +		claims.put("id", member.getId());
claims에 너무 많은 값을 넣는 건 아닌지 확인해보면 좋을 것 같습니다.
오버헤드가 커지기 때문에 필요한 값만 넣어줘도 될 것 같습니다!

2024-02-13 02:30 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/config/WebConfig.java
> +
불필요한 공백이 있습니다

2024-02-13 02:30 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/controller/BoardController.java
> +			boardId = boardService.save(memberId, boardCreateRequest);
이 부분도 AuthAccount 에서 추출할 때 -1L을 주지 말고 -1L을 주는 상황이라면 클래스 안에서 예외를 터뜨리면 될 것 같습니다

지금은 토큰이 없는 경우 작성자 없이 게시글을 저장하는 것 같아보이네요

2024-02-13 02:30 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/controller/dto/BoardResponse.java
> +public class BoardResponse {
record 클래스를 사용해서 변경해주세요~

2024-02-13 02:30 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/domain/Board.java
> +	private Member member;
1. Long memberId 로 간접참조 하는 것과의 차이는 무엇일까요?
2. Member에서 OneToMany로 Board를 가지게 되면 무엇이 다를까요?

2024-02-13 02:30 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/domain/MemberDescription.java
> +	}
아마 서비스에서 해당 메서드를 호출해서 throw RuntimeException을 해줄 것 같은데요
차라리 if문에서 exception을 날려주는 건 어떨까요?

패스워드가 같은지 확인하는 건 도메인 로직 같아보여서요 (제 생각일 뿐입니다 ㅎㅎ)

2024-02-13 02:30 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/service/MemberService.java
> +			throw new MemberNotFoundException("비밀번호가 일치하지 않습니다");
이것도 CustomException으로 수정해주세요

2024-02-13 02:30 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/domain/MemberDescriptionTest.java
> +	void 비밀번호를_검증한다() {
👍

2024-02-13 02:30 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/fixture/BoardFixture.java
> +	public static Board 게시글_생성() {
👍

2024-02-13 02:30 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/service/BoardService.java
> +		board.setMember(member);
setter는 지양해주세요

Member를 먼저 찾고 Board를 생성할 때 생성자 이용하면 setter가 없어도 될 것 같습니다.
그리고 member가 참조한다는 질문에 대해서 여기에 답변을 드리자면 참조 문제를 해결하기 위해서 event를 사용해도 되고 interface를 이용해서 해결을 할 수도 있을 것 같습니다.

인지하신 것처럼 참조가 많아지면 유지보수가 힘들어지고 응집도가 떨어질 수 있습니다.
그래서 위에 방법들을 각자 언제 사용하면 좋을지 공부해보고 적용해보시면 좋을 것 같습니다.

2024-02-13 02:30 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/service/BoardService.java
> +	public Long save(final BoardCreateRequest request) {
이 메서드는 필요 없어보이네요

2024-02-13 10:06 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/component/AuthAccountResolver.java
> +		if (httpServletRequest != null) {
-1L 을 unavailableTokenValue로 변경하였고 exception을 발생시키게 변경하였습니다

2024-02-13 10:07 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/component/JwtTokenProvider.java
> +	private static final long ACCESS_EXPIRED_TIME = 1000 * 60 * 30;            // 30분
수정하였습니다

2024-02-13 10:07 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/component/JwtTokenProvider.java
> +		claims.put("id", member.getId());
처음 작성할 때 getIdFromToken의 리턴 값이 member였다가 password정보 포함 모든 정보를 토큰에 넣는 것은 좋지 않은 방식이라 판단하여 id반환으로 변경하였는데 그 때 못 지운 것 같습니다 
id만 들어가 있도록 수정하였습니다

2024-02-13 10:07 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/config/WebConfig.java
> +
수정하였습니다

2024-02-13 10:07 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/controller/BoardController.java
> +			boardId = boardService.save(memberId, boardCreateRequest);
토큰 없는 경우는 아에 게시글 작성 못하게, exception 발생하게 하였습니다

2024-02-13 10:07 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/controller/dto/BoardResponse.java
> +public class BoardResponse {
수정하였습니다

2024-02-13 10:07 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/domain/Board.java
> +	private Member member;
1. 직접적으로 객체 참조를 하게 되면 객체들 간에 association이 생기게 되고 이 경우 결합도가 증가하게 됩니다 이는 유지보수성에 악영향을 끼칩니다
2. member에서 onetomany를 쓰게 되면 insert를 할 경우 불필요하게 많은 쿼리가 발생합니다

2024-02-13 10:07 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/domain/MemberDescription.java
> +	}
수정하였습니다

2024-02-13 10:07 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/service/MemberService.java
> +			throw new MemberNotFoundException("비밀번호가 일치하지 않습니다");
수정하였습니다

2024-02-13 10:07 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/service/BoardService.java
> +		board.setMember(member);
수정하였습니다

2024-02-13 10:07 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/service/BoardService.java
> +	public Long save(final BoardCreateRequest request) {
삭제하였습니다

2024-02-14 04:15 UTC, sosow0212 approved these changes

2024-02-14 04:15 UTC, merged