최현준 4주차 과제 제출합니다
sosow0212/2024-mju-mentoring pull request #14
Opened 2024-02-12 14:57 UTC by devholic22

2024-02-13 02:40 UTC, sosow0212 requested changes
수고하셨습니다! 여러가지 로그인 방법에 따라 handler를 통해 처리하는게 인상깊네요.
 한 가지 궁금한 점이 있어서 얘기 나눠보고 싶네요~

2024-02-13 02:40 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/domain/Board.java
> +    @ManyToOne(fetch = FetchType.LAZY)
1. Long memberId 로 간접참조하면 무엇이 다를까요?
2. Member에서 OneToMany로 가지게 되면 어떻게 될까요? 언제 OneToMany를 쓰는게 좋을까요?

2024-02-13 02:40 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/support/auth/AuthMemberResolver.java
> +    public Member resolveArgument(final MethodParameter parameter,
반환을 Long id로 주는 것과 Member를 주는 것에 대해서 어떻게 생각하시나요?

컨트롤러 계층에 오기 전에 Service를 통해서 Member를 꺼내줘도 될까요?
때에 따라선 Member가 필요없고 id만 필요할 수도 있을 것 같습니다 그러면 불필요한 조회가 일어날 것 같네요!

2024-02-13 02:40 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/support/auth/handler/AuthMemberHandler.java
> +public interface AuthMemberHandler {
👍

2024-02-13 02:40 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +        Board newBoard = Board.createWithMember(boardText, member);
이것도 그냥 생성자 하나로 만들어도 될 것 같습니다

2024-02-16 10:22 UTC, eom-tae-in approved these changes

2024-03-17 15:16 UTC, merged