최원유 4주차 과제 리팩토링 해봤습니다..!
sosow0212/2024-mju-mentoring pull request #15
Opened 2024-02-15 09:18 UTC by ChoiWonYu

저번 과제 때 적용하지 못한 것들을 적용해봤습니다.
가장 먼저 PathMatcher 인터셉터로 특정 인터셉터를 등록할 때 HTTP 메서드를 지정할 수 있도록 변경했습니다.

또한 저번 구현 때는 Board가 writerId를 가지도록 했는데 게시글은 항상 작성자 이름을 포함한다고 생각해 작성자의 이름과 id를 값타입으로 갖도록 리팩토링 해봤습니다. 이때 boardService에서 Member 애그리거트의 service 객체에 의존하는데 이렇게 설계해도 괜찮은지 궁금합니다..!

deleteAll에 대한 피드백은 이번 풀리 이후 pagination 기능 추가하면서 같이 반영하겠습니다!

2024-02-16 08:02 UTC, sosow0212 requested changes
진짜 군더더기 없이 깔끔하네요~ 몇 부분만 수정해보면 좋을 것 같습니다.
그리고 의견이 듣고 싶어서 하나 코멘트 남겨봤는데 생각 편하게 말씀해주세요~

2024-02-16 08:02 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/domain/Writer.java
> +    private String writerName;
이렇게 하신 이유가 있으신가요?!
설계에 따라서 달라지는 문제지만 그냥 궁금해서 남겨봤습니다 ㅎㅎ

WriterId만 있다면 join으로 작성자까지 가져오면 되지만, 해당 구조로 했을 때엔 역정규화를 해서 조인도 필요없게 하도록 만든 것인가요??

2024-02-16 08:02 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/config/AuthConfig.java
> +            .excludePathPattern(BOARD_URL_PATTERN, HttpMethod.GET);
섬세하네요 👍

2024-02-16 08:02 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/ui/auth/interceptor/AuthCheckInterceptor.java
> +        Optional<String> authorization = Optional.ofNullable(request.getHeader(HEADER_NAME));
Optional로 씌워서 사용하는데 만약 null이라면 어디서 처리를 해주나요? 지금 구조에선 쓰나 안쓰나 큰 차이가 없지 않을까요?

2024-02-16 08:02 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/ui/auth/support/TokenExtractor.java
> +    public static String extractToken(final Optional<String> authorization)
매개변수로 Optional을 주는 건 안티패턴입니다!

2024-02-16 10:21 UTC, eom-tae-in approved these changes
고생하셨습니다~

2024-02-18 13:04 UTC, ChoiWonYu commented on src/main/java/com/mju/mentoring/board/domain/Writer.java
> +    private String writerName;
게시글이라는 애그리거트에서 작성자는 생성부터 삭제까지 생명주기를 같이하는 값이고, 논리적으로 같은 회원이더라도 게시글의 바운디드 컨텍스트에서 작성자는 구분해야 한다고 생각했습니다!

2024-02-18 13:04 UTC, ChoiWonYu commented on src/main/java/com/mju/mentoring/board/domain/Writer.java
> +    private String writerName;
추가로 boardService가 authService에 의존하고 있는 것이 맞는 방식인지에 대해 공부를 해봤습니다.

지금 설계 보다는 board 생성 시점에 쿼리로 member의 이름을 가져와 작성자를 생성하고, member의 변경 사항에 따른 동기화는 이벤트로 구현함으로써 authService에 대한 의존을 더 끊어내는 게 더 좋을 것 같은데 맞는지 궁금합니다!

2024-02-18 13:04 UTC, ChoiWonYu commented on src/main/java/com/mju/mentoring/member/ui/auth/interceptor/AuthCheckInterceptor.java
> +        Optional<String> authorization = Optional.ofNullable(request.getHeader(HEADER_NAME));
TokenExtractor의 extractToken메서드에서 null처리를 해주고 있습니다
인터셉터와 argumentResolver 에서 공통적으로 null일 수도 있는 header의 Authorization 을 가져오는데, 
이 null 처리 작업을 TokenExtractor에서 같이 해주고 싶었습니다. 지금보다 좋은 방식이 있는지 궁금합니다..!

2024-02-18 13:04 UTC, ChoiWonYu commented on src/main/java/com/mju/mentoring/member/ui/auth/support/TokenExtractor.java
> +    public static String extractToken(final Optional<String> authorization)
```java
Optional<String> authorization = Optional.ofNullable(request.getHeader(HEADER_NAME));
```
이에 대한 null 처리를 따로 해주는 것이 나을까요..??

2024-02-21 08:05 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/domain/Writer.java
> +    private String writerName;
지금 구조라면 Board를 저장할 때 멤버의 유저네임도 조회해서 저장하는 것 같네요.
그러기보다는 멤버id를 저장한다면 (토큰을 이용해 추출한) 저장할 때 의존할 필요는 없어보입니다!

다만 조회할 때 Join을 한다면 코드상에서의 의존은 없지 않을까요!

그리고 두번째 라인에 대한 답변은 이벤트로 의존을 끊어내는 것이 더욱 응집성면에서도, 참조관계면에서도 좋아보입니다 ㅎㅎ

2024-02-21 08:06 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/ui/auth/interceptor/AuthCheckInterceptor.java
> +        Optional<String> authorization = Optional.ofNullable(request.getHeader(HEADER_NAME));
그 부분은 제가 잘 확인하지 못했네요! 다시 확인하니 지금 방식 괜찮아보입니다 👍

2024-02-21 08:09 UTC, sosow0212 approved these changes
리뷰 보고 이해 안되는 점 있다면 DM 한 번 더 부탁드립니다!
수고하셨습니다 ㅎㅎ

2024-02-21 08:09 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/ui/auth/support/TokenExtractor.java
> +    public static String extractToken(final Optional<String> authorization)
매개변수 넘기기 전에 null 처리를 해주는 건 어떨까요? 그러면 TokenExtractor는 토큰이 무조건 존재한다는 가정하에 동작할 것 같습니다. null 처리를 지금 나눈 부분 중 어디서 하는게 적절한지 생각해보면 좋을 것 같아요. 그렇게 된다면 그 클래스에서는 Null 처리에 대한 책임이 있고, 그 이후에 클래스에서는 불필요한 null처리는 하지 않아도 되니깐요.

2024-02-21 08:09 UTC, merged