5주차 미션 제출하겠습니다!
sosow0212/2024-mju-mentoring pull request #16
Opened 2024-02-25 08:10 UTC by ChoiWonYu

- [x] RestDocs 적용
- [x] 조회수 추가
- [x] 동시성 제어
- [x] 인덱스 설정 

기존 MvcTest에 Rest Docs를 추가하고, 미션 요구사항 구현했습니다!

DB에 1000개의 더미 데이터를 넣어, LIKE 조회 쿼리에 대한 실행 계획을 인덱스 적용 전 후로 비교해봤습니다.
아래는 전 후 실행 계획 스크린샷입니다!
<img width="1095" alt="스크린샷 2024-02-24 오후 10 54 28" src="https://github.com/sosow0212/2024-mju-mentoring/assets/93238308/65fe7e74-ba8b-4912-bb85-0327480f6a97">
<img width="1080" alt="스크린샷 2024-02-24 오후 10 55 16" src="https://github.com/sosow0212/2024-mju-mentoring/assets/93238308/51ab1154-851e-438c-9316-d93f03313d87">

동시성 처리에 대한 테스트를 ExecutorService와 CountDownLatch를 이용해 테스트해봤는데 혹시 더 좋은 방법이 있는지 궁금합니다..!

추가로 조회수가 변경 감지로 증가하는 값이다보니 repository infratructure 슬라이스 테스트에서 검증하지 못한 어려움이 있었는데 슬라이스 테스트에서 락에 대한 테스트는 보통 어떻게 처리되는지도 궁금합니다

2024-02-28 08:17 UTC, sosow0212 requested changes
크 처음 했는데 완전 잘했네요 REST Docs까지 번거로웠을텐데 수고하셨습니다 👏
여러가지 문제가 생길 수 있는 부분에 대해서 적어봤는데 어떻게 생각하는지 궁금합니다!

조회수가 변경감지로 이뤄진다면, 해당 부분에 대한 테스트는 service에서 진행해보면 어떨까요? repository에서는 쿼리가 의도한대로 나왔는지 정도만 확인해도 되지 않을까 개인적으로는 생각합니다!
정답은 없지만 이에 대해서 어떻게 생각하시는지도 답변해주시면 좋을 것 같습니다.

2024-02-28 08:17 UTC, sosow0212 commented on src/docs/asciidoc/boards.adoc
> +== 게시글 생성 (POST /boards)
REST Docs까지.. 👍

2024-02-28 08:17 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/application/BoardService.java
> +        Board board = findById(id);
findById 메서드에 보면 비관적 락을 사용하는 jpa 조회 메서드를 호출하는 것 같습니다.
그럼 다른 메서드에서 사용할 때에도 모두 락을 걸어 조회를 할 것 같은데, 따로 분리하는 건 어떨까요?

그리고 낙관적락은 언제 사용하면 좋을까요? 비관적 락에 비해 장단점은 무엇이고, 예외 처리는 어떻게 하면 좋을지도 고민해보면 좋을 것 같습니다~

2024-02-28 08:17 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/application/BoardService.java
> +        board.viewBoard();
조회수 치팅 가능성이 있을 것 같습니다.
현재는 단일 서버이니 메모리 캐싱을 이용해서 치팅을 방지할 수도 있을 것 같습니다. 
(ex. Map = {key: boardId, value : List.of(조회한 유저1, ...)}, 매일 자정마다 Map.clear()... 등등)

추후에 스케일아웃을 했다면 위에 방법은 해결이 되지 않을 수 있는데 이런 경우는 또 어떻게 해결하면 좋을까요?

2024-02-28 08:17 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/application/BoardService.java
> +        boards.forEach(board -> board.verifyWriter(writerId));
좋네요!
Boards라는 일급컬렉션 객체를 만들어서 조회한 데이터를 넣어서 검증은 일급 컬렉션 도메인 안에서 진행해주면 어떨까요?
추후에 예외 사항이 생기더라도 책임을 분리할 수 있을 것 같아요

2024-02-28 08:17 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/application/BoardService.java
> +        boards.forEach(board -> board.changeWriter(writerId, newWriterName));
쿼리가 n번 나갈까요? (n == 작성한 게시글 수)

2024-02-28 08:17 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/domain/Board.java
> +@Table(indexes = @Index(name = "board_title_index", columnList = "title"))
어떤 쿼리에서 title을 사용하나요? title을 인덱스로 건 이유가 무엇인가요?
추가적으로 `select ... where content = ? AND title = ?` 쿼리가 있는 경우 이 쿼리를 최적화 시킨다고 할 때 조건절에 맞춘 인덱스의 순서도 중요할까요?

2024-02-28 08:17 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/application/BoardService.java
> +        Board board = findById(id);
++ 게시글 조회를 100명이 동시에 하는 경우 해당 락을 건 경우 조회는 순차적으로 이뤄질까요?  속도는 어떨까요?

2024-02-28 08:17 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/infrastructure/BoardJpaRepository.java
> +    })
오 쿼리 힌트를 넣은 근거는 무엇일까요?!

2024-02-28 08:17 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/infrastructure/BoardJpaRepository.java
> +    @Query("SELECT b FROM Board b WHERE b.writer.writerId = :writerId")
쿼리를 별도로 넣은 이유가 있을까요??

2024-02-28 08:17 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/application/auth/AuthService.java
> +        member.changeNickName(request.newNickname());
게시글 이름을 바꾼 후에 게시글에 해당하는 작성자를 바꾸기 위한 이벤트 발송을 안 하는 것 같네요!

2024-02-28 08:17 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/ui/BoardAcceptanceTestFixture.java
> +    protected ExtractableResponse 여러번_동시에_게시글을_조회한다(final String url) {
E2E에서도 동시성을 제어하기 위한 테스트를 진행하고 있네요!
배포를 할 때 테스트가 돌아간다고 가정을 하면, 지금과 같은 테스트는 배포할 때 테스트 수행 시간 때문에 오래 걸리지 않을까요?

물론 동시성을 테스트 하는 방법은 좋지만, 이런 부분도 고려를 해본다면 좋을 것 같습니다!
정답은 없는 문제지만, 예를들어 개발 과정에서 ServiceIntegration 테스트를 작성하고, 배포 전 @Test를 주석해놓는다거나 등등 다른 방법도 여러가지 있는데 한 번 생각해보면 좋을 것 같습니다 ㅎㅎ

2024-02-29 16:45 UTC, ChoiWonYu commented on src/main/java/com/mju/mentoring/board/application/BoardService.java
> +        Board board = findById(id);
이후에 주신 피드백 모두 참고해서 락을 좀 더 자세하게 공부해보겠습니다!

2024-02-29 16:45 UTC, ChoiWonYu commented on src/main/java/com/mju/mentoring/board/application/BoardService.java
> +        board.viewBoard();
이번엔 말씀해주신대로 Map을 이용해 기능을 추가하고, 이후에 Redis로 해당 기능 적용해보겠습니다!

2024-02-29 16:45 UTC, ChoiWonYu commented on src/main/java/com/mju/mentoring/board/application/BoardService.java
> +        boards.forEach(board -> board.verifyWriter(writerId));
일급 컬렉션이 그렇게 사용될 수 있겠네요..! 감사합니다!

2024-02-29 16:45 UTC, ChoiWonYu commented on src/main/java/com/mju/mentoring/board/domain/Board.java
> +@Table(indexes = @Index(name = "board_title_index", columnList = "title"))
이후 페이지네이션을 추가하면서 검색 기능을 구현할 때 title로 검색을 할 계획이었습니다!

title이 중복이 적은 컬럼이기도 하고, LIKE 쿼리가 많이 사용될 것 같아 title을 인덱스로 지정했습니다!

인덱스가 조건절에 쓰이는 것이 중요하고, 인덱스가 사용되는 것에 대해 순서는 중요하지 않은 것으로 알고 있습니다

2024-02-29 16:45 UTC, ChoiWonYu commented on src/main/java/com/mju/mentoring/board/infrastructure/BoardJpaRepository.java
> +    })
데드락을 방지하기 위해 timeout을 지정했습니다!

2024-02-29 16:45 UTC, ChoiWonYu commented on src/main/java/com/mju/mentoring/board/infrastructure/BoardJpaRepository.java
> +    @Query("SELECT b FROM Board b WHERE b.writer.writerId = :writerId")
작성자를 값타입으로 분리해서 메서드 이름이 findAllByWriterWriterId가 되어버리는데 간단하게 하기 위해 쿼리를 사용했습니다..!

2024-02-29 16:45 UTC, ChoiWonYu commented on src/main/java/com/mju/mentoring/member/application/auth/AuthService.java
> +        member.changeNickName(request.newNickname());
이름을 바꾸는 것은 멤버 도메인이 핵심로직이라고 판단해 멤버 도메인에서 이벤트 발송까지 하게 했습니다..! 이벤트 발송은 응용 계층에서 하는 게 나을까요??

2024-02-29 16:45 UTC, ChoiWonYu commented on src/test/java/com/mju/mentoring/board/ui/BoardAcceptanceTestFixture.java
> +    protected ExtractableResponse 여러번_동시에_게시글을_조회한다(final String url) {
시간이 많이 걸리면 개발 과정에서만 테스트하는 방법도 있군요..! 감사합니다

2024-02-29 16:45 UTC, ChoiWonYu commented on src/main/java/com/mju/mentoring/board/application/BoardService.java
> +        boards.forEach(board -> board.changeWriter(writerId, newWriterName));
writeId와 WriterName을 값으로 가지게 해서 N번의 변경 감지 update 쿼리가 나갈 것 같긴 합니다.

빈도가 높은 작업도 아니라 변경 감지로 처리하려고 했는데 성능상 벌크 연산으로 처리하는 것이 나을까요??

2024-03-01 01:08 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/application/BoardService.java
> +        boards.forEach(board -> board.changeWriter(writerId, newWriterName));
게시글을 많이 작성한 헤비 유저라면 쿼리가 많이 나갈 것 같긴합니다
벌크연산이 성능적으로는 좋은데 빈도가 높지 않다고 생각하면 패스하셔도 됩니다! 
선택은 상황에 맞게하면 되니 어떤 장단점이 있는지만 파악하면 될 것 같습니다

2024-03-01 01:10 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/domain/Board.java
> +@Table(indexes = @Index(name = "board_title_index", columnList = "title"))
[해당 글](https://jojoldu.tistory.com/243)을 참조해보면 더 좋을 것 같습니다 !

2024-03-01 01:14 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/application/auth/AuthService.java
> +        member.changeNickName(request.newNickname());
도메인은 도메인 로직만 수행하고, 비즈니스 로직(이벤트 발송 ex. 닉네임을 바꾸면 게시글의 작성자도 바뀐다)과 같은 건 응용 서비스에서 해주는 게 좋을 것 같습니다!

위에 예시에선 서비스 레이어에서 `Member의 닉네임을 바꾸고(member) : 도메인 -> 이벤트를 발송 : 서비스 -> 이벤트 수신 및 Board의 작성자를 변경 : 서비스 -> Board.updateWriter(...) : 도메인` 과 같이 하는게 더 적절해보입니다!

2024-03-05 06:43 UTC, ChoiWonYu commented on src/main/java/com/mju/mentoring/board/domain/Board.java
> +@Table(indexes = @Index(name = "board_title_index", columnList = "title"))
순서도 중요하군요..! 감사합니다!

2024-03-06 05:16 UTC, sosow0212 approved these changes
수고하셨습니다~
몇 가지 고민해보면 좋겠다 싶은 부분들은 중간중간에 코멘트 남겨봤습니다.

이미 미션 이상으로 충분히 잘하셔서 Approve 하겠습니다!
확인하고 Merge 하시면됩니다 👍

2024-03-06 05:16 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/infrastructure/BoardJpaRepository.java
> +        @Param("newWriterName") final String newWriterName);
이것도 일급컬렉션으로 해결할 수 있을 것 같은데 쿼리가 n개 나가서 처리량을 늘리기 위해서 이렇게 하신거죠??

2024-03-06 05:16 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/infrastructure/MemoryViewCountManager.java
> +    private final Map<Long, Set<Long>> views = new HashMap<>();
Map을 이용하고 스케줄링으로 초기화 하면서 치팅을 막은게 인상적이네요~
여기서 추가적으로 생각해보면 좋을 것 같아서 적고 갑니다.

1. 만약 사용자가 늘어나서 스케일아웃을 하게 되었다면 해당 로직은 어떻게 바꾸는 게 좋을까요?

2. 스케줄링 주기를 바꿔야한다면 코드를 재배포 해야할까요?

2024-03-06 05:16 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/application/BoardServiceTest.java
> +    private final ViewCountManager viewCountManager = Mockito.mock(ViewCountManager.class);
1. 직접 이번에 mock을 사용하면서 느낀 장점과 단점은 뭐고 fake 방식은 무엇이 다르다고 생각하시나요??

2. 해당 테스트 클래스를 통해서 어떤 것을 검증하고 싶으셨나요? (ex. 결과값, 실행 흐름 ...)

2024-03-06 05:16 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/application/BoardServiceTest.java
> +        given(viewCountManager.isAlreadyRead(anyLong(), anyLong())).willReturn(true);
`given().willReturn()`, `when().thenReturn()`의 차이는 무엇일까요?

2024-03-11 10:18 UTC, ChoiWonYu commented on src/main/java/com/mju/mentoring/board/infrastructure/BoardJpaRepository.java
> +        @Param("newWriterName") final String newWriterName);
넵 모든 수정에 대해 변경 감지 작업을 수행하는 것보다 벌크 연산으로 처리하는 것이 더 효율적이라고 생각했습니다.

2024-03-11 10:18 UTC, ChoiWonYu commented on src/main/java/com/mju/mentoring/board/infrastructure/MemoryViewCountManager.java
> +    private final Map<Long, Set<Long>> views = new HashMap<>();
스케일아웃을 하게 되면 Map 데이터를 공유할 수 없으므로 redis를 이용해야 할 것 같습니다. 구현 예정입니다!

redis를 적용할 때 해당 구현 방식에서 스케줄링 주기를 동적으로 결정할 수 있도록 수정해보겠습니다!

2024-03-11 10:18 UTC, ChoiWonYu commented on src/test/java/com/mju/mentoring/board/application/BoardServiceTest.java
> +        given(viewCountManager.isAlreadyRead(anyLong(), anyLong())).willReturn(true);
given().willReturn()은 BDDMockito에서 제공하는 메서드입니다. 특정 메서드의 리턴값을 지정하는 것은 given에 더 어울리는 행위라고 생각해 given().willReturn()을 사용했습니다

2024-03-11 10:18 UTC, ChoiWonYu commented on src/test/java/com/mju/mentoring/board/application/BoardServiceTest.java
> +    private final ViewCountManager viewCountManager = Mockito.mock(ViewCountManager.class);
1. mock 객체는 의존 객체에 대한 구현체 없이도 의도한 실행 흐름과 행위 검증 등을 편하게 할 수 있다는 장점이 있지만, 객체 간 협력 관계에 대한 의존이 생기고 신뢰도가 떨어진다는 단점이 있는 것 같습니다. 
Fake방식은 mock 방식과 달리 테스트를 위한 가짜 구현체를 실제로 만들어 테스트의 신뢰도를 높여준다는 장점이 있지만, 해당 객체를 실제로 구현해야 하기 때문에 개발 시간 증가와 fake 객체에 대한 테스트 코드도 필요할 수 있어 이에 대한 부담도 있을 것 같습니다.

2. 실행의 흐름이 의도한 대로 흘러가는지 확인하는 것이 가장 검증하고 싶은 요소였습니다.

2024-03-11 10:19 UTC, merged