김남훈 5주차 미션 제출합니다
sosow0212/2024-mju-mentoring pull request #17
Opened 2024-02-27 14:25 UTC by zoid79

조회수 추가하였고 동시성 제어는 비관적 락으로 하였습니다 
아래 스크린 샷은 더미게시글 10000개 중 view가 많은 10개를 불러올 때 views에 인덱스가 있을 떄와 아닐 때 성능비교를 하였습니다

2024-02-28 14:48 UTC, zoid79 commented
![스크린샷 2024-02-27 231313](https://github.com/sosow0212/2024-mju-mentoring/assets/87366543/1e1cac9d-0e0b-4b5e-ad92-b1adf8079bef)
![스크린샷 2024-02-27 231214](https://github.com/sosow0212/2024-mju-mentoring/assets/87366543/19d08300-00fc-467f-8af0-340b3aa0fb41)
![스크린샷 2024-02-27 231243](https://github.com/sosow0212/2024-mju-mentoring/assets/87366543/02cf2a7c-d72c-4ff0-a4c0-52e1af281c8f)
사진 첨부합니다

2024-03-01 01:05 UTC, sosow0212 requested changes
이전 리뷰에서 언급했던 부분들이 잘 지켜지지 않는 것 같은데 이 부분 확인 부탁드리고, 인덱스 적용도 안 된 것 같습니다.
몇 부분만 확인해보시고 수정해주세요~
테스트도 그렇고 어려울텐데 처음보다 많이 나아진게 보이네요
수고하셨습니다!

2024-03-01 01:05 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/domain/Board.java
> +		this.member = member;
viewCount는 처음에 0과 같이 기본 값이 있을텐데 생성자에서 값을 받기보다는 기본 값을 설정해주는 것이 좋지 않을까요?

2024-03-01 01:05 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/domain/Member.java
> +	public boolean writerValidation(Member member) {
매개변수로 Long memberId 를 받는 것과 Member 객체 자체를 받는 것은 뭐가 다를까요?

2024-03-01 01:05 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/domain/MemberDescription.java
> +	private String loginId;
loginId를 Column으로 설정하신 이유가 무엇인가요? 저 값은 저장할 필요가 없지 않을까요?

2024-03-01 01:05 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/domain/MemberDescription.java
> +			throw new MemberNotFoundException("비밀번호가 일치하지 않습니다");
비밀번호가 일치하지 않는 건 NotFound가 아니라 다른 응답을 줘야할 것 같네요

2024-03-01 01:05 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/domain/MemberDescription.java
>  	public boolean isValidPassword(String password) {
지금 일치하지 않으면 예외 발생하고, 일치하면 true를 반환하는데
반환을 void로 하고 예외처리만 해도 될 것 같습니다

2024-03-01 01:05 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/infrastructure/MemberJpaRepository.java
> +	Optional<Member> findMemberByMemberDescription_LoginId(String memberId);
메서드명에 언더바가 있는데, 자바에선 카멜케이스를 사용해서 바꿔야할 것 같아요

2024-03-01 01:05 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/service/BoardService.java
> +		}
if/else가 불필요하게 들어가있네요
도메인 로직에서 처리할 수 있어 보입니다

2024-03-01 01:05 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/service/BoardService.java
> +		}
여기도 마찬가지로 불필요해보입니다

2024-03-01 01:05 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/service/MemberService.java
> +		Member member = new Member(signUpRequest.memberId(), signUpRequest.username(), signUpRequest.password(),
request에서 memberId를 받는게 이상해보이네요
id는 pk로 가지고 있었는데, memberId는 어떤 의도로 사용되는 건지 잘 모르겠습니다 ㅠ

2024-03-01 01:05 UTC, sosow0212 commented on src/main/resources/application-local.yml
> +  expired_time: 1800000
provider에서 이 값을 사용하지 않네요!

2024-03-01 01:05 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/controller/BoardAcceptanceTest.java
> +        });
이 값만 검증해도 되나요?
5개의 게시글을 저장했으면 size, value 등등 검증하는게 좋습니다

2024-03-01 01:05 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/controller/BoardControllerTest.java
> +import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
지난 리뷰에서도 그랬듯이 import에서 와일드카드는 지양해주세요 ~

2024-03-01 01:05 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
테스트 격리가 안 돼서 순서대로 실행하는 것 같은데 이 방법 말고 다른 방법은 없을까요? 다른 메서드가 추가되면 기존 순서가 변경될 수도 있고 지금 방법은 좋아보이지 않네요

2024-03-01 01:05 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/service/MemberServiceTest.java
> +}
이것도 예전 리뷰에 남겼는데 끝에 파일 개행이 있어야합니다

2024-03-01 01:05 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/domain/Board.java
Board에 인덱스 적용이 안 되어있습니다

2024-03-02 18:03 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/domain/Board.java
MySql에다가만 추가하였는데 수정했습니다

2024-03-02 18:03 UTC, zoid79 commented on src/test/java/com/mju/mentoring/board/service/MemberServiceTest.java
> +}
pull request할때 충돌이 발생해서 현 코드 복붙하면서 개행이 날아간 것 같습니다

2024-03-02 18:03 UTC, zoid79 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
해당 클래스에서 테스트코드가 문제가 생겨서 해결하고자 사용하였는데 이제는 상관 없어서 지금 제거하였습니다

2024-03-02 18:04 UTC, zoid79 commented on src/test/java/com/mju/mentoring/board/controller/BoardControllerTest.java
> +import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
수정하였습니다

2024-03-02 18:04 UTC, zoid79 commented on src/test/java/com/mju/mentoring/board/controller/BoardAcceptanceTest.java
> +        });
size 검증 추가하였습니다

2024-03-02 18:04 UTC, zoid79 commented on src/main/resources/application-local.yml
> +  expired_time: 1800000
테스트코드에서만 작동이 되지 않는데 해결하는 방법을 몰라서 원래 있던대로 하였습니다... 어떻게 해야할까요..? 테스트코드에서만 못 긁어옵니다 test yml에도 추가하였는데도

2024-03-02 18:04 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/service/MemberService.java
> +		Member member = new Member(signUpRequest.memberId(), signUpRequest.username(), signUpRequest.password(),
위에 적은대로 전에 memberId라고 쓴것이 현 loginId입니다 수정했습니다

2024-03-02 18:05 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/service/BoardService.java
> +		}
수정했습니다

2024-03-02 18:05 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/service/BoardService.java
> +		}
수정했습니다

2024-03-02 18:05 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/infrastructure/MemberJpaRepository.java
> +	Optional<Member> findMemberByMemberDescription_LoginId(String memberId);
수정했습니다

2024-03-02 18:05 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/domain/MemberDescription.java
>  	public boolean isValidPassword(String password) {
수정했습니다

2024-03-02 18:05 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/domain/MemberDescription.java
> +			throw new MemberNotFoundException("비밀번호가 일치하지 않습니다");
BadCredentialsException 으로 새로운 exception만들었습니다

2024-03-02 18:05 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/domain/MemberDescription.java
> +	private String loginId;
로그인 할 때 사용하는 아이디는 필요하지 않나요..? memberId에서 logingId로 바뀐것을 여쭤보시는거라면 member에 있는 id를 테스트코드 안돌아가는 탓에 memberid랑 id랑 둘 다 테스트 해보면서 column명 안 겹치게 loginId로 하였습니다

2024-03-02 18:05 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/domain/Member.java
> +	public boolean writerValidation(Member member) {
저 부분이 member안에 memberdescription에서 사용할 loginId인데 네이밍을 바꾸면서 저 부분만 변경이 안됐네요
이해를 못했는데 MemberDescription을 new해서 받은 것과 그 안의 멤버변수를 넘기는 것과 무슨 차이냐고 여쭤보신건가요?
일단 저 부분도 테스트코드때문에 바꾸다가 바꾸지 못한 부분이고 제가 이해한걸론 자바로 봤을 때 전자는 value를 받는거고 후자는 reference를 받는 것으로 알고 있습니다

2024-03-02 18:05 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/domain/Board.java
> +		this.member = member;
아 처음에 테스트 코드가 안돌아가서 저런 영향도 있나 바꾸다가 가만히 놔둔게 그대로 제출됐네요 수정했습니다

2024-03-04 06:00 UTC, sosow0212 requested changes
몇 가지만 더 확인해주세요!!
과제 하시느라 수고 많으셨습니다~

2024-03-04 06:00 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/service/BoardService.java
> +	private EntityManager entityManager;
이건 왜 붙이신걸까요?!

2024-03-04 06:00 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/domain/Member.java
> +	public boolean writerValidation(Member member) {
아뇨! 이미 pk로 id가 있는데, description안에 loginId(아마 토큰으로 분리한 id 같습니다!)도 있어서 중복아닌가 해서 여쭤봤습니다.

loginId가 없어도 될 것 같은데 어떤 목적에서 사용하는 건지 궁금해서요!

2024-03-04 06:00 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/controller/BoardController.java
> +		@RequestBody final BoardUpdateRequest request) throws AccessDeniedException {
1. AccessDeniedException은 왜 붙이셨나요?
2. 만약 예외가 터진다면 어디서 해결해주나요 현재?

2024-03-04 06:00 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/domain/Member.java
> +	public void isValidPassword(String password) throws BadCredentialsException {
void로 변경했다면 네이밍을 변경해줘야겠네요

2024-03-04 06:00 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/domain/Member.java
> +	public void isValidPassword(String password) throws BadCredentialsException {
그리고 저기서 throw를 하는거보다는 if문을 만들어서 내부에서 throw를 해주는게 좋지 않을까요?
정확한 조건을 명시하고 터지는 예외니깐요

2024-03-04 06:00 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/exception/MemberNotWriterException.java
> +		super("비밀번호가 일치하지 않습니다");
예외 메시지가 다른 것 같네요

2024-03-04 06:00 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/exception/BadCredentialsException.java
> +		super("비밀번호가 일치하지 않습니다");
얘도 예외 메시지가 이상한 것 같습니다!

2024-03-04 06:00 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/domain/Board.java
> +@Table(name = "Board", indexes = {@Index(name = "idx_views", columnList = "views")})
오 views에 인덱스를 건 이유가 무엇인가요? 현재 쿼리중에 views가 들어가는 쿼리가 있나요?

2024-03-04 09:54 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/domain/Member.java
> +	public boolean writerValidation(Member member) {
id는 1,2,3,4 자동으로 생겨나는 id입니다(멤버는 모르는), loginId는 회원가입, 로그인 할 때 입력하는 id입니다

2024-03-04 10:02 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/controller/BoardController.java
> +		@RequestBody final BoardUpdateRequest request) throws AccessDeniedException {
사실 프론트엔드에서 버튼을 안 보이게 하거나 그 단에서 처리를 해도 될 것 같지만 일단 제가 사용한 의도는 게시글을 쓴 사람이 아닌 다른 사람이 update를 시도하였을 때 발생하는 exception입니다

2024-03-04 10:06 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/domain/Board.java
> +@Table(name = "Board", indexes = {@Index(name = "idx_views", columnList = "views")})
아직은 없지만 해당 게시판을 만든다고 하였을 때 조회수 정렬은 후에 필요할 것이라고 생각되어서 view에 인덱스를 달았습니다

2024-03-17 15:16 UTC, merged