유저 미션 구현
sosow0212/2024-mju-mentoring pull request #20
Opened 2024-04-02 17:49 UTC by ChoiWonYu

구현한 플로우는 다음과 같습니다.
미션에 처음 도전할 땐 그 미션 애그리거트에서 이벤트를 발송하고 미션 진행도 애그리거트에서 이벤트를 수신해 진행도를 생성합니다. 자원에 대한 CRUD 작업이 일어나면 이벤트가 발송되고, 미션을 진행하고 있을 경우 그 미션의 진행도가 올라갑니다. 

ProgressRepositoryImpl처럼 spring-data-jpa와 querydsl를 이용해 구현하고 test할 때 fake 객체를 어떻게 만들어야 하는지 궁금합니다. 그리고 미션을 도전할 때 미션 서비스 객체가 이벤트를 이용해 진행도 애그리거트에서 진행도를 생성하게 하는데 이런 식으로 이벤트를 사용하는 것이 맞는 방법인지 궁금합니다..!

2024-04-03 04:14 UTC, sosow0212 requested changes
몇 부분에 대해서 코멘트 남겨놨습니다!
한 번 확인해보시고 궁금하신 점 있으면 편하게 DM 주세요 👍

2024-04-03 04:14 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/application/BoardService.java
> +        Events.raise(BoardOperateEvent.of(writerId, savedBoard.getId(), CREATE));
도메인의 작업마다 OperationType을 주는 게 인상깊네요 ㅎㅎ
중복 코드를 줄일 수 있고 조금 더 세분화 시킬 수 있는 것 같습니다.

저도 하나 배우고 갑니다!

2024-04-03 04:14 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/mission/domain/mission/ChallengeMissionEvent.java
> +package com.mju.mentoring.mission.domain.mission;
도메인과 같은 패키지에 넣은 이유가 있는지 궁금합니다!

2024-04-03 04:14 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/mission/domain/progress/MissionProgress.java
> +public class MissionProgress {
사용자는 미션을 하나밖에 못 받도록 설계를 하신 것인가요?
만약에 여러 개 받을 수 있다고 가정하면 어떻게 설계하면 좋을까요?

++ 멤버가 미션 3개를 클리어하고 보상을 개별 수령할 수도 있고, 전체 수령도 할 수 있을지도 궁금합니다 ㅎㅎ

2024-04-03 04:14 UTC, sosow0212 commented on src/main/resources/data.sql
> +values (1, '5번 이상 게시글 작성하기', 'BOARD', 'CREATE', 5, 5);
TARGET과 OPERATE_TYPE 정체가 여기서 발견되네요!
좋은 방법인 것 같습니다 👍

2024-04-03 04:14 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/mission/infrastructure/progress/ProgressQueryDslRepositoryTest.java
> +    void when_() {
메서드 네이밍 깜빡하신 것 같습니다!

2024-04-03 04:14 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/mission/domain/progress/ProgressRepository.java
> +public interface ProgressRepository {
네이밍 때문에 헷갈렸습니다 ㅠㅠ MissionProgressRepository로 바꾸는 건 어떨까요?

2024-04-03 04:14 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/mission/application/progress/ProgressService.java
> +            challengerId, missionId);
이 부분은 int count = progressRepo.find~ 로 받으면 더 빠르지 않을까요?
누가 잘 정리해놨는데 참고해보시면 좋을 것 같습니다! [링크](https://hungseong.tistory.com/73)

2024-04-03 04:14 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/mission/application/progress/ProgressEventHandler.java
> +    @Async
1. 비동기 처리를 하는데 쓰레드풀 설정은 안해도 될까요?
2. 메서드 실행 중에 서버가 다운된다면 어떻게 될까요? 실패 경우를 다루지 않아도 될지 궁금합니다!

TODO: 쓰레드 풀 설정을 마쳤다면, 비동기 메서드를 사용할 때 데드락이 생길 여지가 있는지 확인해보고 어떻게 막을 수 있을지와 다른 방법으로 방지할 수 없는지도 찾아보면 좋을 것 같습니다.

2024-04-03 04:14 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/mission/application/mission/MissionService.java
> +                    new ChallengeMissionEvent(challengerId, missionId, mission.getGoal())),
1. 이벤트 네이밍은 과거시제로 사용합니다~
2. 미션이 완료된 경우 처리는 안해도 되나요?
3. 그럴 일은 적겠지만 보상과 관련되어 남겨봅니다! 유저가 매우 빠르게 challengeMission 메서드를 작동 시킨다면 치팅이 일어날 수 있을까요?

2024-04-03 04:14 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/mission/domain/progress/CurrentInfo.java
> +    public boolean canReceiveReward() {
보상 수령은 아직 구현하지 않은거죠?!

2024-04-03 04:14 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/mission/infrastructure/progress/ProgressQueryDslRepository.java
> +public class ProgressQueryDslRepository {
질문에 대한 답을 여기에 남겨보자면 Querydsl을 사용하면 저도 Fake 객체를 사용할 때 애매한 점이 많이 있었습니다.

실제로 조인을 해서 값을 가져오는데 정확하지 않거나 이런 부분이 있겠죠?
이건 제 개인적인 의견이지만 어차피 Fake객체를 사용하는 이유가 행위 검증을 하기 위함이라면 필요한 데이터들만 Fake에서 반환하도록하고, 알 수 없는 값 혹은 사용하지 않아도 되는 값은 임의로 작성해도 될 것 같습니다. 

정확한 검증은 E2E에서 진행되고, 현재 상황에서는 레포지토리 통합 테스트도 잘 수행하고 있어서 문제가 될 부분은 없어보입니다!

2024-04-18 15:52 UTC, ChoiWonYu commented on src/main/java/com/mju/mentoring/mission/domain/progress/CurrentInfo.java
> +    public boolean canReceiveReward() {
넵 보상 수령은 아직 구현 전입니다!

2024-04-18 15:52 UTC, ChoiWonYu commented on src/main/java/com/mju/mentoring/mission/domain/progress/MissionProgress.java
> +public class MissionProgress {
MissionProgress는 어떤 유저가 어떤 미션을 진행중인지 알려주기 위한 객체입니다! 따라서 여러 개의 미션을 받을 수 있고, 개별 수령, 전체수령 모두 가능합니다!

2024-04-18 15:52 UTC, ChoiWonYu commented on src/main/java/com/mju/mentoring/mission/application/mission/MissionService.java
> +                    new ChallengeMissionEvent(challengerId, missionId, mission.getGoal())),
미션이 완료된 경우에 대한 처리는 MIssionProgress 도메인에서 하고 있습니다!

2024-04-19 08:20 UTC, sosow0212 approved these changes
수고하셨습니다
큰 문제가 없어 보여서 Approve할게요!

2024-04-19 08:20 UTC, sosow0212 commented on src/main/resources/application.yml
> +        queue-capacity: 8
1. 다음과 같이 설정한 이유가 있을까요?

2. 쓰레드풀 설정을 상황마다 다르게 하고 싶다면 어떻게 해야할까요?

2024-04-19 08:20 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/mission/application/progress/ProgressEventHandler.java
> -    @Async
1. 비동기 방식에서 동기 방식으로 바꾼 이유가 있나요?
2. 동기 방식이라면 현재 트랜잭션은 어디서 시작되고 어디서 끝날까요?

2024-04-23 01:29 UTC, ChoiWonYu commented on src/main/java/com/mju/mentoring/mission/application/progress/ProgressEventHandler.java
> -    @Async
1. 위 기능에서 이벤트를 사용한 이유는 미션과 진행도의 의존을 느슨하게 하기 위해서 입니다. 따라서 한 번에 이뤄져야 하는 기능들이기 때문에 동기 방식으로 바꿨습니다!
2. 이벤트를 publish하는 미션에서의 읽기 트랜잭션과 subscribe하는 미션 진행도 생성 트랜잭션이 별개로 동작하는 것으로 알고 있습니다. 위에서 각 트랜잭션이 다른 자원을 처리하기 때문에 한 트랜잭션에서 처리할 필요가 없다고 생각했습니다!

2024-04-24 15:15 UTC, merged