Zoid79
sosow0212/2024-mju-mentoring pull request #4
Opened 2024-01-19 09:48 UTC by zoid79

테스트 코드 다 돌아가게 리팩토링 하였습니다
Board CRUD 완료 했습니다
Member Table 만들었습니다

테스트 코드 controller, repository 단에서 get 메소드 제외 완료하였습니다

2024-01-19 10:19 UTC, sosow0212 requested changes
처음인데 테스트도 작성하시고 고생많으셨습니다.
리뷰 보시고 반영해주세요~

2024-01-19 10:19 UTC, sosow0212 commented on .gitignore
> +/src/main/generated
QClass ignore 잘 해주셨습니다!

2024-01-19 10:19 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/controller/BoardController.java
> +    @Autowired
19줄과 20줄 사이에 개행 한 칸이 필요합니다~

```
class AAClass {
// 개행 추가하고
    private final ..~
}
```

이런식으로 컨벤션 맞춰가면 될 것 같습니다. 다른 클래스 포함해서 다시 수정해주세요~

2024-01-19 10:19 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/controller/BoardController.java
> +        return ResponseEntity.created(URI.create("/boards/" + boardId))
/boards/id 로 로케이션 주는 이유는 무엇인가요?
Board 객체를 dto로 씌워서 반환하는 거랑 뭐가 다를까요?

2024-01-19 10:19 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/controller/BoardController.java
> +    @PutMapping("/boards/{id}")
@Put과 @Patch의 차이를 공부해보면 좋을 것 같습니다

2024-01-19 10:19 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/controller/dto/BoardResponse.java
> +}
https://jojoldu.tistory.com/673

2024-01-19 10:19 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/controller/dto/BoardResponse.java
> +
어떤 건 개행을 추가하고 어떤 건 넣지 않으셨는데 이유가 있을까요??

2024-01-19 10:19 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/domain/Board.java
> +
불필요한 개행이 있습니다

2024-01-19 10:19 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/infrastructure/BoardJpaRepository.java
> +import java.util.Optional;
이 import가 해당 클래스에서 사용되나요? 커밋 전에 사용하지 않는 import는 모두 제거해주세요

2024-01-19 10:19 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/service/BoardService.java
> +                .orElseThrow(() -> new IllegalArgumentException("게시글이 없습니다"));
이 부분은 추후에 기능에 생긴다면 여러곳에서 사용될 것 같은데 메서드 분리하는게 좋을 것 같습니다.

2024-01-19 10:19 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/service/BoardService.java
> +        System.out.println(request.getContent());
System.out.println()은 지양해주세요!
왜 그럴까요?

2024-01-19 10:19 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/ControllerTests.java
> +import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
구글 컨벤션에 따르면 import에 *과 같은 와일드카드는 지양하는게 좋습니다!

2024-01-19 10:19 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/ControllerTests.java
> +        assertThat(board.getContent()).isEqualTo(updateBoard.getContent());
여러 값을 검증할 땐 Assertions의 softly를 사용해보는 건 어떨까요

2024-01-19 10:19 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/ControllerTests.java
> +    }
1번을 지우는 이유가 있나요?
개별 실행 시에는 작동이 되지만, 테스트 전체 실행하면 깨진다면 `테스트 격리` 검색하셔서 공부하고 적용해보시면 좋을 것 같습니다

2024-01-19 10:19 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/ControllerTests.java
> +    void updateTest() throws Exception {
given-when-then 패턴을 공부해서 적용해보는 건 어떨까요?

2024-01-19 10:19 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/ControllerTests.java
> +        assertThat(boards.size()==0);
항상 모든 코드는 불필요한 Import문 제거 및 코드 정렬하는 습관을 가져주세요

-> size() == 0
--> 이 부분도 hasSize() 메서드로 대체 가능하겠네요

2024-01-19 10:19 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/ControllerTests.java
> +
불필요한 개행

2024-01-19 10:19 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/RepositoryTests.java
> +class RepositoryTests {
클래스 명을 RepositoryTests로 하신 이유가 있나요?

보통 {class명}Test 라는 네이밍을 사용합니다.
현재와 같다면 클래스가 추가된다면 헷갈릴 것 같습니다

2024-01-19 10:19 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/RepositoryTests.java
> +    BoardRepositoryImpl boardRepository;
이 부분도 레포지토리만을 테스트 하는 것이라면 BoardRepository로 선언한다면 DI를 자동으로 해주지 않을까요?

2024-01-19 10:19 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/RepositoryTests.java
> +    void putTest() {
BoardRepository에 put이라는 메서드가 없다면 굳이 안하셔도 됩니다

클래스에서 사용하는 메서드만 테스트해주셔도 됩니다

2024-01-20 04:07 UTC, eom-tae-in requested changes
고생하셨습니다.

2024-01-20 04:07 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/exam/board/domain/Board.java
> +    public Board(String title, String content) {
일관성있게 final 키워드를 붙여주세요

2024-01-20 04:07 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/exam/board/controller/BoardController.java
> +
이 메서드에만 개행을 추가한 이유가 있을까요? 
일관성있게 메서드를 작성하는 것이 좋을거 같아요

2024-01-22 10:09 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/controller/BoardController.java
> +
네 수정하였습니

2024-01-22 10:09 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/domain/Board.java
> +    public Board(String title, String content) {
수정하였습니다

2024-01-22 10:09 UTC, zoid79 commented on src/test/java/com/mju/mentoring/RepositoryTests.java
> +    void putTest() {
확인 후 제거하였습니다

2024-01-22 10:10 UTC, zoid79 commented on src/test/java/com/mju/mentoring/RepositoryTests.java
> +    BoardRepositoryImpl boardRepository;
수정하였습니다

2024-01-22 10:10 UTC, zoid79 commented on src/test/java/com/mju/mentoring/RepositoryTests.java
> +class RepositoryTests {
BoardRepositoryTests로 수정하였습니다.
레이어 별로 test코드 작성하는 것으로 알아서 그렇게 하였습니다

2024-01-22 10:10 UTC, zoid79 commented on src/test/java/com/mju/mentoring/ControllerTests.java
> +
수정하였습니다

2024-01-22 10:10 UTC, zoid79 commented on src/test/java/com/mju/mentoring/ControllerTests.java
> +        assertThat(boards.size()==0);
코드 정렬의 경우 저 부분만 지웠다 내려도 저 칸 수를 유지하네요 이유를 모르겠습니다

2024-01-22 10:10 UTC, zoid79 commented on src/test/java/com/mju/mentoring/ControllerTests.java
> +    void updateTest() throws Exception {
해당 패턴을 학습한 수 각 파트별로 개행 한줄 씩 추가하였습니다

2024-01-22 10:10 UTC, zoid79 commented on src/test/java/com/mju/mentoring/ControllerTests.java
> +    }
수정하였습니다

2024-01-22 10:10 UTC, zoid79 commented on src/test/java/com/mju/mentoring/ControllerTests.java
> +        assertThat(board.getContent()).isEqualTo(updateBoard.getContent());
수정하였습니다

2024-01-22 10:10 UTC, zoid79 commented on src/test/java/com/mju/mentoring/ControllerTests.java
> +import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
수정하였습니다

2024-01-22 10:10 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/service/BoardService.java
> +        System.out.println(request.getContent());
System.out.println()은 동기화로 인해 여러 쓰레드에서 사용할 경우 lock으로 인한 성능저하가 발생하는 것으로 알고 있습니다

2024-01-22 10:10 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/service/BoardService.java
> +                .orElseThrow(() -> new IllegalArgumentException("게시글이 없습니다"));
수정하였습니다

2024-01-22 10:11 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/infrastructure/BoardJpaRepository.java
> +import java.util.Optional;
수정하였습니다

2024-01-22 10:11 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/domain/Board.java
> +
수정하였습니다

2024-01-22 10:11 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/controller/dto/BoardResponse.java
> +
단순히 체크 못하여 발생한 것 같습니다 수정하였습니다

2024-01-22 10:11 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/controller/dto/BoardResponse.java
> +}
확인하였습니다

2024-01-22 10:11 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/controller/BoardController.java
> +    @PutMapping("/boards/{id}")
공부하였습니다
PUT의 경우에는 데이터에 null값이 있을 경우 update 시에 null값이 반영이 되고 PATCH의 경우에는 변경사항이 null이 포함되어 있다면 해당 부분은 원 데이터 대로 두고 나머지 부분만 update를 하는 것 이라는 답을 얻었습니다

2024-01-22 10:11 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/controller/BoardController.java
> +        return ResponseEntity.created(URI.create("/boards/" + boardId))
전자의 경우 게시글 작성을 하였을 때 해당 게시글, 데이터를 조회할 수 있는 경로를 전달하는 것이고
dto로 반환을 하면 생성된 데이터 자체를 전달하는 것으로 알고 있습니다

2024-01-22 10:11 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/controller/BoardController.java
> +    @Autowired
수정하였습니다

2024-01-25 06:13 UTC, closed without merging