1주차 최현준 제출합니다.
sosow0212/2024-mju-mentoring pull request #5
Opened 2024-01-19 10:01 UTC by devholic22

## 작업 내용
* 게시글 (Board)에 대한 CRUD 작업을 개발 완료하였습니다.
  * `게시글 전체 조회`는 개발하지 않고 `단일 조회`만 작성하였는데, 요청하실 경우 반영하겠습니다.
  * DTO로는 자바17의 `레코드`를 사용하였습니다. 레코드를 사용하니 `@NoArgsConstructor`나 `@Getter` 등을 사용하지 않아도 기본적으로 제공되어 코드를 많이 줄일 수 있겠다 생각하여 적용하였습니다.
  * 전체적인 객체에 대한 생성은 정적 팩터리 메서드를 활용하였습니다.
  * 글의 수정 경우, `updateTitle`과 `updateContent`처럼 따로 분리하였습니다. 하나의 메서드에서 두가지를 모두 변경하기보다는 한 가지씩 변경하는 게 하나의 메서드에서 한 역할만 수행하는 것에 더 가깝다고 생각했습니다.
  * 생성과 수정에서는 해당 작업 이후 반영된 id만 알 수 있도록 id만을 DTO에 담아두었습니다. 실제 웹과 연결이 된다면 리다이렉트 되는 경우가 많기 때문입니다.
* 멤버 (Member)에 대한 테이블 정의를 개발 완료하였습니다.
  * 멤버의 id임을 테이블에서 바로 알 수 있도록 `@Column`으로 별칭을 지정하였습니다.
  * 정적 팩터리 메서드를 활용하였습니다.

## 알게 된 점
* 스프링 데이터 JPA 인터페이스인 `BoardJpaRepository`를 만들었고, 이 인터페이스를 참조하는 구현체로 `BoardJpaRepositoryImpl` 로 작성하였으나, 슬랙에 공유한 것과 같이 `셀프 참조` 이슈가 발생하여 `JpaBoardRepositoryImpl`로 이름을 변경하였습니다. ([관련 정리 글](https://devwriter.tistory.com/24))
* 개인적으로 프로젝트를 하던 때와 달리 실수로 `POST 요청을 하였는데 null이 저장`되는 상황이 발생했습니다. 찾아보니 파라미터 인자에 `@RequestBody`를 작성하지 않았기 때문이었습니다. 해당 문제에 대해서도 [글](https://devwriter.tistory.com/25)을 정리하였습니다.

## 궁금한 점 & 기타
* BoardService의 `update` 경우, 전달받은 id로 게시글을 찾은 다음 내용을 업데이트하고 있습니다. 때문에 id로 게시글을 찾는 `find` 함수를 이용하게 하였으나, 생각해보니 이렇게 하면 코드의 중복은 제거할 수 있겠으나 `트랜잭션의 접근` 수준이 서로 다르기 때문에 (find에서는 `readOnly = true`, update에서는 `readOnly = false`) 트랜잭션 간 충돌이 날 수 있겠다는 생각이 들기도 합니다. 이 부분에 대해 의견을 나누고 싶습니다.
* 예외 처리, API 응답 구조에 대해서도 적용하고자 하였으나, 이것을 적용하기 위해서는 많은 내용이 변경될 것 같아 우선 제가 개인적으로 예전에 작성했던 [해당 글](https://velog.io/@devholic/Spring-API-%EC%9D%91%EB%8B%B5-%ED%98%95%EC%8B%9D-%EC%A0%95%EC%9D%98%ED%95%98%EA%B8%B0-ExceptionHandler) (API 응답 및 예외처리)에 대해 어떠한 의견을 가지고 계신지 먼저 여쭤보고 싶습니다.
* 리뷰 이후 테스트 작업도 진행하겠습니다.

2024-01-19 10:37 UTC, sosow0212 requested changes
수고하셨습니다!

예외를 구조에 대해서 어떻게 생각하는지 질문 하신 것은 블로그 글에 응답 구조에 대해서 여쭤보시는 것인가요?

그 부분은 정해진 것이 없고 팀원들과 협의하고 구조적으로 응답하는 것이 필요하다면 그 때 Dto를 씌워 보내면 될 것 같습니다.

둘 다 알고 계신 것 같으니 이번 멘토링에서는 편하신대로 하셔도 될 것 같아요!

2024-01-19 10:37 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/controller/BoardController.java
> +    public ResponseEntity<BoardSearchResponse> find(@PathVariable final Long id) {
find는 Board에서 어떻게 find한다는 것일까요?
연관되는 댓글이 있을 수도 있고 이미지가 될 수 있고, 그렇다면 id는 뭘 의미하는지 메서드명 혹은 매개변수를 명확히 해주면 좋겠네요

2024-01-19 10:37 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/controller/dto/BoardCreateResponse.java
> +public record BoardCreateResponse(Long id) {
record 👍

2024-01-19 10:37 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/domain/BoardRepository.java
> +    void deleteById(final Long id);
별건 아니지만.. 매개변수 명을 통일해주는 건 어떨까요 ㅋㅋㅋㅋ

2024-01-19 10:37 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/infrastructure/JpaBoardRepositoryImpl.java
> +    }
id를 주는 건 서비스가 무엇을 반환하는지 알고 있는 것일까요?
이 경우 void, Board 중에 뭘 줘야할까요?

2024-01-19 10:37 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +    }
질문하신 거 여기다가 답변하겠습니다.
이번 미션이야 간단해서 생각을 못하셨을 수도 있으셨을 것 같습니다.

하지만 보통 게시글을 조회하는 경우 게시글만 줄 수도 있겠지만 댓글도 줄 수 있지 않을까요? 만약 게시글 + 댓글을 준다면 어떻게 해야할까요? 이 부분은 고민해보시면 좋을 것 같습니다.

그리고 컨트롤러에서 find를 사용하고 update에서도 find를 사용하는데요.
이 두 메서드가 중복이라서 Transaction 어노테이션을 붙이지 않으신 것 같습니다. 어차피 여기 Transactional을 붙여도 update에서 트랜잭션 분리가 되지 않아서 상관은 없지만 저 같으면 `public Board findById()`라는 네이밍으로 `return findBoard(id).orElseThrow...` 이런 식으로 줄 것 같습니다.

내부에서 find해주는 메서드는 private으로 빼고요

2024-01-19 10:37 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/domain/Member.java
> +    public static Member of(final String username, final String nickname, final String password) {
생성자가 있는데 정팩메를 사용하신 이유가 있을까요?

2024-01-19 10:37 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/domain/Member.java
> +@Entity
요건 무시하셔도 되지만 보통 저는 class명에 가까울 수록 중요한 어노테이션을 붙입니다.
```
...
@Entity
public class Member
```

위에는 어찌됐던 상관 없지만 그래도 가깝게 두면 어노테이션이 많은 경우 가독성이 좋은 것 같습니다!

2024-01-19 10:37 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +        targetBoard.updateContent(request.content());
업데이트의 역할은 하나로 봐서 굳이 분리하지 않고 묶어도 되지 않을까요?

업데이트 해야할 컬럼이 10개가 된다면 10번 쓰는게 오히려 실수할 수도 있을 것 같습니다

2024-01-19 10:37 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +    }
++ 생각해보니 find의 경우 readOnly=true 속성이 있겠네요
그러면 그냥 `return boardRepository.findById(id)
                .orElseThrow(() -> new IllegalStateException("해당 게시물이 없습니다."))` 이 부분을 private 메서드로 분리하고 사용하는게 좋겠네요!

2024-01-19 10:37 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/domain/Board.java
> +    public static Board of(final String title, final String content) {
여기도 생성자가 있는데 정팩메를 사용할 이유는 없어보입니다

2024-01-19 10:37 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/controller/BoardController.java
> +    @PutMapping("/{id}")
HTTP 메서드에서 `PUT`, `PATCH` 메서드의 차이점은 무엇일까요?

그리고 추가적으로 GET에서 Request 로 데이터를 받는 것과 파람으로 받는 것의 차이와 뭘 지향해야하는지도 공부해보시면 좋을 것 같습니다.

2024-01-19 11:05 UTC, devholic22 commented on src/main/java/com/mju/mentoring/board/domain/BoardRepository.java
> +    void deleteById(final Long id);
반영 완료하였습니다! `BoardRepository` 같은 경우 충분히 `Board` 에 관한 저장소라는 느낌을 주기 때문에 `boardId` 대신 `id`로 대체하였습니다 :)

2024-01-19 12:08 UTC, devholic22 commented on src/main/java/com/mju/mentoring/board/infrastructure/JpaBoardRepositoryImpl.java
> +    }
void가 더 적절하다고 생각됩니다! 이상하게 설계했었네요..
제 생각으로는 가장 밑단에 있는 리포지토리는 넘겨받은 엔티티를 영속화하는 데에만 집중하면 충분하다고 생각됩니다.
그렇기 때문에 서비스 단에서 생성된 엔티티의 id를 가져오는 행위는 서비스에서만 하면 될 것 같습니다.

2024-01-19 12:16 UTC, devholic22 commented on src/main/java/com/mju/mentoring/member/domain/Member.java
> +@Entity
제 원래 의도도 중요한 것일수록 붙이려 하였으나, 습관적으로 어노테이션을 붙이면서 순서를 지키지 않았었네요 ㅠㅠ
그동안 어노테이션들에 대한 선언 규칙 같은 것을 원했었는데, 피드백 감사합니다!

2024-01-19 12:21 UTC, devholic22 commented on src/main/java/com/mju/mentoring/member/domain/Member.java
> +    public static Member of(final String username, final String nickname, final String password) {
그간 `생성자 대신 무조건 정적 팩터리 메서드만을 써야겠다` 싶었는데, [정적 팩터리 메서드가 가지는 장점들에 대한 글](https://velog.io/@cjh8746/%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9CStatic-Factory-Method)들을 보니 정적 팩터리 메서드가 제공해주는 장점들이 DTO에는 별로 적용될만한 게 없는 것임을 알게 되었습니다.

`어떤 기술이나 기법을 사용하려고 할 때 그것을 취할 경우 장점이 명확한 경우에만 사용해야겠다`고 느끼게 되었습니다! 👀

2024-01-19 12:50 UTC, devholic22 commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +        targetBoard.updateContent(request.content());
말씀하신대로 `글과 본문에 대한 업데이트`는 하나의 메서드로 묶어도 될 것 같습니다!

하지만 조금 더 생각해봤을 때 궁금한 점이 있습니다.

현재 `BoardUpdateRequest` 같은 경우는 제목 (title)과 본문 (content) 만을 가집니다.
그리고 컨트롤러에서는 `PUT /boards/{id}` 이런 식으로 되어 있고, `BoardUpdateRequest`를 인자로 가집니다.

그런데 만약 `Board`에 제목, 본문 이외에 사진, 파일 등의 데이터가 새로 추가되고, 이렇게 `미디어에 대한 수정`이 추가로 필요하게 된다면 방법은 두 가지가 있을 것 같습니다.

1. 미디어 수정에 대한 요청 DTO를 따로 만들고, 컨트롤러 & 서비스 & 도메인의 로직을 각각 추가한다.
2. BoardUpdateRequest에 미디어에 관한 속성도 추가한다.

첫 번째 방법은 수정이긴 하지만 데이터의 종류 (텍스트 or 미디어)에 따른 최소한의 구분을 넣은 예가 되어 `기존에 있던 제목 & 본문 수정 API를 변경하지 않아도 되는 장점`이 있으나, 한편으로는 간접적으로 영향이 있지 않을까 생각됩니다. 예컨대 스프링에서는 하나의 경로에 대한 동일한 HTTP Method를 여러 개 가지는 것을 허용하지 않는 것으로 알고 있는데, 그렇게 된다면 이 충돌을 피하기 위해 `PUT boards/{id}/text`, `PUT boards/{id}/media`라는 경로를 나눠야 할 것 같습니다. 이런 경우 지금 단계에서는 지금의 경로를 가져도 괜찮은 것인지, 아니면 이러한 향후 있을 확장성에 대비하기 위해 미리 경로를 `PUT boards/{id}/text`로 바꿔두는 게 좋을지 고민이 됩니다.

두 번째 방법은 말씀하신대로 "수정"이라는 하나의 큰 역할로 봐서 하나의 메서드만 호출하면 되는 장점이 있지만, 기존에 작성했던 제목 & 본문 수정 API에 미디어 수정이 안으로 들어가게 되는 단점이 있을 것 같습니다.

아무래도 첫 번째 방법이 더 괜찮을 것 같다는 생각이 드는데, 이 점에 대해서 말씀해주실 수 있을까요?

2024-01-19 14:23 UTC, devholic22 commented on src/main/java/com/mju/mentoring/member/domain/Member.java
> +    public static Member of(final String username, final String nickname, final String password) {
정적 팩터리 메서드를 쓰는 이유로는 `생성 목적을 다양하게 할 수 있다`는 점이 있는데, 스프링 MVC의 경우에는 요청 DTO를 통해 생성하는 것 하나밖에 없다는 점에서 굳이 사용하지 않아도 될 듯 하네요..!

재윤 님께서도 스프링 MVC 환경에서는 정적 팩터리 메서드를 사용하지 않으시는 편인지 궁금합니다.

일단 DTO에 존재하던 정적 팩터리 메서드는 삭제 조치 하였습니다! (DTO 및 레코드 특성상 목적이 `데이터 전달`이라는 하나의 목적만 있고, 필드에 따른 생성자를 자동으로 지원하기 때문에 삭제하였습니다.)

2024-01-20 03:36 UTC, devholic22 commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +    }
private으로 걸어둔 메서드는 `@Transactional`의 영향을 받지 않는다는 사실을 배울 수 있었습니다! ([참고 글](https://velog.io/@ljks789/spring%EC%97%90%EC%84%9C-transactional%EC%97%90-private%EC%9D%B4-%EB%A8%B9%ED%9E%88%EC%A7%80-%EC%95%8A%EB%8A%94-%EC%9D%B4%EC%9C%A0))

말씀하신대로 게시글을 주는 경우와 게시글과 댓글을 주는 경우를 구분하는 것은 쉽게 생각이 서지 않는데, 이런 상황이 생겼을 때 어떻게 처리할 수 있을지 고민해보겠습니다.

2024-01-20 03:39 UTC, devholic22 commented on src/main/java/com/mju/mentoring/board/controller/BoardController.java
> +    public ResponseEntity<BoardSearchResponse> find(@PathVariable final Long id) {
수정 완료하였습니다!

컨트롤러, 서비스에서 모두 `find` & `delete`를 `findById`, `deleteById`로 수정하였는데, 제 생각으로는 해당 메서드를 호출하는 곳이 `BoardController`, `BoardService` 이렇게 `Board`로부터 시작되므로 충분히 메서드명이나 매개변수가 `findById`더라도 어떤 id를 의미하는지 (= Board의 id)를 쉽게 유추할 수 있을 것이라 생각되어 작성했습니다.

다만 이곳과 아래에서 말씀해주셨듯 댓글과 이미지 등 구성 요소가 늘어났을 때 이들을 구분하기 위한 방법에서는 아직 명확한 생각이 떠오르는 것 같지 않아 고민해보겠습니다..!

2024-01-20 03:40 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +    }
그게 아니라
```
@Tx
public .. updateBoard(req, boardid) {
   Board b = findBoard(boardId);
  b.update(req);
}

@Tx(readOnly = true)
public findBy~(boardId) {
   return findBoard(boardId);
}

private Board findBoard(id) {
  return repo.findById(id)
                     .orElseThrow();
}
```

이렇게 해도 된다는 말입니다!
트랜잭션이 의도한대로 다 태워집니다 ㅎㅎ

2024-01-20 03:44 UTC, devholic22 commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +    }
아 네네 이해했습니다! 제가 살짝 잘못 표현드렸었네요 😅
제가 처음에 작성했던 코드는 readOnly false로 되어있던 update에서 readOnly true로 되어있는 find를 사용했는데, private 메서드로 분리해두면 호출할 상위 메서드들이 가지는 각자의 트랜잭션으로 각각 할당이 되니 말씀하신 방법으로 하는 게 맞겠다는 생각이 들었습니다 :)

2024-01-20 03:46 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/domain/Member.java
> +    public static Member of(final String username, final String nickname, final String password) {
저는 정적팩토리 메서드를 완전 애용하는 편이에요

근데 생성자나 빌더로 할 수 있다면 굳이 하진 않습니다.

그리고 기본적인 생성전략이 있는 경우 (ex. 멤버 생성시 기본 등급은 MEMBER_ROLE로 설정, 초기 값을 설정 해주는 경우)에는 정적 팩토리 메서드로 메서드에 의미를 부여해서 사용하는 편입니다.

DTO 같은 경우에는 데이터 전달을 목적으로 하니 어차피 객체를 넣어도 의존 문제에서 큰 상관 없다고 생각해서 저는 정팩메로 객체 하나만 넘겨서 편리하게 사용하고 있습니다.

정답은 아니지만 정리하면 다음과 같스빈다.

1. 정적 팩토리 메서드 사용하는 경우
- 생성 전략이 있어서 의미 부여해주는 경우
- DTO 같이 참조 관계가 생겨도 큰 문제가 없는 클래스에서 편리하게 사용하기 위해서

2. 사용하지 않는 경우
- 생성자에 있는 것 그대로 옮겨오는 경우 (단, 뜻이 있는 경우라면 제외)

2024-01-20 03:51 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +        targetBoard.updateContent(request.content());
일단 RESTful 원칙은 참고만 하는 것입니다!
무조건 따라야된다가 아니라 팀의 컨벤션에 따라 얼마든지 바뀌어도 된다라고 생각하시면 됩니다.

미디어에 대한 수정만 필요한 경우이건 아니건
프론트에서는 변경된 게시글의 request만 보내주고 서버에선 그걸 처리만 하면 되지 않을까요?

예를 들어서 Board(title, content, images) 로 구성되어 있을 때
images만 바꾸는 경우 images만 request에 보내주는 것이 아닌 바뀌지 않은 title, content도 같이 보내줘도 상관 없다는 말입니다.
업데이트 때 jpa에선 어차피 덮어씌우기가 되니 아무런 문제가 되지 않아보이네요!

별개로 관리하는 경우 말씀하신 것처럼 endpoint가 자원만큼 늘어날 수 있는데 이런 방법은 좋아보이진 않습니다.

2024-01-20 03:52 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +        targetBoard.updateContent(request.content());
이건 별개로

```
NumberMakerComponentTest > 숫자가 100보다 큰 경우 true 를 반환한다 FAILED
    org.opentest4j.AssertionFailedError at NumberMakerComponentTest.java:[31](https://github.com/sosow0212/2024-mju-mentoring/actions/runs/7591868252/job/20680498970?pr=5#step:6:32)

NumberMakerTest > 숫자가 5보다 큰 경우 true 를 반환한다 FAILED
    java.lang.NullPointerException at NumberMakerTest.java:26

NumberMakerTest > 숫자가 5보다 작은 경우 false 를 반환한다 FAILED
    java.lang.NullPointerException at NumberMakerTest.java:39
```

이렇게 뜨는데 혹시 충돌하면 그냥 해당 클래스 지워버리고 커밋해주세요~

2024-01-20 03:53 UTC, devholic22 commented on src/main/java/com/mju/mentoring/member/domain/Member.java
> +    public static Member of(final String username, final String nickname, final String password) {
말씀해주신 것을 보고 추가로 궁금한 점이 있습니다!

빌더 패턴을 추가로 말씀해주셨는데, 다른 분께 코드 리뷰를 받았을 때 `빌더 패턴은 추후 유지보수 시 놓치는 부분이 생길 수 있어 실무에서는 빌더 패턴보다 생성자 패턴을 더 선호하는 경향이 있다`고 하시기도 하더라구요. 이 부분은 객체 생성 시 들어가는 인자의 갯수가 3개 이상이라면 놓치는 부분이 생길 수 있더라도 빌더 패턴으로 처리해주는게 효과적일 것 같다는 생각을 가지고 있는데, 이 부분에 대해서는 어떻게 생각하시는지 궁금합니다.

2024-01-20 04:11 UTC, eom-tae-in requested changes

2024-01-20 04:11 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/board/controller/BoardController.java
> +    public ResponseEntity<BoardUpdateResponse> updateText(@PathVariable Long id,
final 키워드가 누락된 거 같네요. 
final 붙여주세요~

2024-01-20 04:19 UTC, devholic22 commented on src/main/java/com/mju/mentoring/board/controller/BoardController.java
> +    public ResponseEntity<BoardUpdateResponse> updateText(@PathVariable Long id,
헉 컨트롤러는 직접 작성하다보니 미처 붙이지 않은 곳도 있었네요 감사합니다!

2024-01-20 04:19 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/domain/Member.java
> +    public static Member of(final String username, final String nickname, final String password) {
물론 생성자가 더 안전하긴 하죠 ㅋㅋ 그건 저도 동의합니다

2024-01-27 10:08 UTC, sosow0212 requested changes
몇 부분 리뷰 남겼습니다~ 
확인하시고 질문한 내용에 대해서 답변해주시면 좋을 것 같습니다.

작업하시느라 수고 많으셨습니다!
근데 이왕 해본거 인수테스트까지 공부하고 진행해보면 어떨까요?

2024-01-27 10:08 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/controller/BoardController.java
> +                .map(board -> new BoardSearchResponse(board.getId(), board.getTitle(), board.getContent()))
이정도면 정적 팩토리 메서드를 사용해도 되지 않을까요.. ㅎㅎ
Dto에 객체 의존이 생기는 문제가 있지만 어차피 정보 전달용으로 사용하니깐요! 큰 문제가 없을 것 같습니다

2024-01-27 10:08 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/domain/Board.java
> +    }
VO개념이기 때문에, BoardText.update() 보다는 새로 객체를 생성하는 방식에 대해서는 어떻게 생각하시나요?
각자 어떤 장단점이 있을까요

2024-01-27 10:08 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/domain/BoardText.java
> +public class BoardText {
EqualsHashcode는 없어도 될까요?!

2024-01-27 10:08 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/exception/BoardExceptionHandler.java
> +import static com.mju.mentoring.global.exception.GlobalExceptionHandler.createExceptionResponseWithStatusAndMessage;
오 글로벌로 뺐나요? 좋네요 여러 패키지에서도 사용할 수 있겠네요!

2024-01-27 10:08 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +    public Board searchById(final Long id) {
serch는 검색일 것 같은데 find는 어떨까요? 네이밍이 겹친다면 잘 조율해서 바꾸는게 좋을 것 같습니다

2024-01-27 10:08 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/controller/BoardControllerTest.java
> +                .andExpect(jsonPath("$.id").value(newBoard.getId()))
값 검증 좋네요 👍 어차피 이 부분은 REST Docs 배우면 거기서 하시면 됩니다
되게 비슷한데 한 번 공부하고 적용해보시면 어떨가요?

2024-01-27 10:08 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/controller/BoardControllerTest.java
> +
예외에 대한 질문을 하셔서 여기다가 남길게요

> 현재 id에_맞는_게시글이_없으면_예외가_발생한다 (컨트롤러)에서, .andExpect(jsonPath(”$.error”).exists())를 붙이면 실패되는 오류를 겪고 있습니다. 원래는 BoardNotFoundException이 터졌기 때문에 error가 나와야 하는데 그러지 않는 것이 왜 그런지 파악 중입니다.

지금 mock을 사용하고 있는데 when().thenThrow() 같은 메서드를 사용해서 서비스를 태우면 예외가 발생하게 한 후에 그걸 mockmvc에서 검증하면 될 것 같습니다.

2024-01-27 10:08 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +            softly.assertThat(boards.size()).isEqualTo(2);
`(boards).hasSize(2)`로도 검증 가능합니다

2024-01-27 10:08 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +        assertThat(boardJpaRepository.findById(targetBoard.getId()).isEmpty()).isTrue();
`assertThat(boardJpaRepository.findById(targetBoard.getId())).isEmpty();` 이렇게 해도 될 것 같네요!

2024-01-27 10:08 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/service/BoardServiceTest.java
> +            softly.assertThat(saveOne.getTitle()).isEqualTo(titleOne);
제목만 검증하는데 usingRecursive를 활용하면 어떨까요?

2024-01-27 10:08 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/service/BoardServiceTest.java
> +    void 게시글을_수정한다() {
수정할 때 게시글이 없는 경우 발생하는 예외는 검증 안해도 될까요?
리팩토링이 커진다면 중요할 수 있을 것 같아요

2024-01-27 10:08 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/support/CleanDatabase.java
> +@TestExecutionListeners(value = {CleanDatabaseListener.class,}, mergeMode = TestExecutionListeners.MergeMode.MERGE_WITH_DEFAULTS)
`@TestExecutionListeners(value = {CleanDatabaseListener.class,}, mergeMode = TestExecutionListeners.MergeMode.MERGE_WITH_DEFAULTS)` 이 부분은 어떤 역할을 할까요? mergeMode는 무엇일까요?

2024-01-27 10:08 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/support/CleanDatabaseListener.java
> +public class CleanDatabaseListener extends AbstractTestExecutionListener {
`AbstractTestExecutionListener`는 무슨 역할을 할까요?

2024-01-28 01:42 UTC, eom-tae-in approved these changes
고생하셨습니다~

2024-01-28 01:42 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/board/domain/Board.java
> +    public Board(final String title, final String content) {
title과 content를 받는 생성자를 정적 팩토리 메서드로 만드는 건 어떨까요?
그러면 네이밍을 부여해서 boardText로 Board를 생성한다는 의도를 잘 드러낼 수 있을 것 같아요!

2024-01-28 16:08 UTC, devholic22 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +            softly.assertThat(boards.size()).isEqualTo(2);
감사합니다! 같은 의미를 요약할 수 있게 되었네요 :)

2024-01-28 16:09 UTC, devholic22 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +        assertThat(boardJpaRepository.findById(targetBoard.getId()).isEmpty()).isTrue();
반영했습니다!

2024-01-29 11:07 UTC, devholic22 commented on src/main/java/com/mju/mentoring/board/domain/Board.java
> +    }
현재 BoardText에서의 update 함수를 새로운 BoardText를 반환하는 방식으로 하였는데 의도하신 것과 같은 방향인지 궁금합니다..!

2024-01-29 11:08 UTC, devholic22 commented on src/test/java/com/mju/mentoring/board/controller/BoardControllerTest.java
> +                .andExpect(jsonPath("$.id").value(newBoard.getId()))
말씀하신 대로 다음 멘토링 전까지 REST Docs에 대해서도 적용해보도록 하겠습니다!

2024-01-29 11:28 UTC, devholic22 commented on src/test/java/com/mju/mentoring/board/service/BoardServiceTest.java
> +    void 게시글을_수정한다() {
반영했습니다! 더불어 삭제할 때에도 게시글이 없을 경우의 예외 검증을 추가하고 없는 게시글의 조회 테스트명도 변경하였습니다 :)

2024-01-29 13:40 UTC, devholic22 commented on src/test/java/com/mju/mentoring/board/support/CleanDatabaseListener.java
> +public class CleanDatabaseListener extends AbstractTestExecutionListener {
`AbstractTestExecutionListener`는 `beforeTestClass`, `afterTestMethod` 등 테스트들이 돌아가는 도중에 원하는 행위들을 작성하도록 해 줍니다.

말씀하신 내용을 보기 위해 더 찾아보던 도중, 왠지 JUnit에서 기본으로 제공하는 `@BeforeEach`, `@AfterEach`와 순서가 어떻게 구분될까라는 궁금증이 들어 확인해보았고, 아래 결과 순서로 나왔습니다.

* AbstractTestExecutionListener의 `prepareTestInstance`
    * (TestInstance: 아래 TestClass의 구현체)
*  AbstractTestExecutionListener의 `beforeTestClass` 
    * (TestClass: `class com.mju.mentoring.board.infrastructure.BoardJpaRepositoryTest` 등)
*  JUnit의 `beforeAll`
* AbstractTestExecutionListener의 `beforeTestMethod`
    * (TestMethod: `void com.mju.mentoring.board.infrastructure.BoardJpaRepositoryTest.게시글을_저장한다()` 등)
* JUnit의 `beforeEach`
* AbstractTestExecutionListener의 `beforeTestExecution`
* 테스트
* AbstractTestExecutionListener의 `afterTestExecution`
* JUnit의 `afterEach`
* AbstractTestExecutionListener의 `afterTestMethod`
* JUnit의 `afterAll`
*  AbstractTestExecutionListener의 `afterTestClass`

또한 추가적으로 찾아보니 AbstractTestExecutionListener는 TestContext를 통해 ApplicationContext에 접근할 수 있다는 점이 JUnit과의 차이점임을 알았고, TestContext에서 publishEvent 메서드로 미루어보아 테스트 환경에서도 `이벤트를 처리`할 수 있는 점이 가장 큰 특징 같습니다. (이 과정에서 왜 마지막에 Listener가 붙었는지도 알 것 같습니다.) (직접 이벤트를 검증해보려고 했는데 아직 그 부분까지는 쉽지 않은 듯 합니다 ㅠㅠ)

2024-01-29 14:07 UTC, devholic22 commented on src/test/java/com/mju/mentoring/board/support/CleanDatabase.java
> +@TestExecutionListeners(value = {CleanDatabaseListener.class,}, mergeMode = TestExecutionListeners.MergeMode.MERGE_WITH_DEFAULTS)
TestExecutionListeners는 저희가 정의할 AbstractTestExecutionListener를 상속받는 자식 클래스들을 테스트 실행 시 등록시켜주는 역할을 합니다. (AbstractTestExecutionListener가 TestExecutionListener을 구현합니다.) value는 해당되는 자식 클래스들을 뜻하며, `mergeMode`는 `default로 존재하는 다른 리스너들`을 대체할 것인지를 설정하는 역할을 합니다. 이것은 `REPLACE_DEFAULTS`, `MERGE_WITH_DEFAULTS`가 있으며, default로 존재하는 다른 리스너들의 예시로는 아래 것들이 있습니다.

* DirtiesContextTestExecutionListener (컨텍스트를 변경하여 다시 로드)
* TransactionalTestExecutionListener (트랜잭션 관리)
* DependencyInjectionTestExecutionListener (의존성 주입)

이 중, TransactionalTestExecutionListener의 코드를 보니 스프링이 테스트 환경에서 어떻게 트랜잭션을 제공하는지 더 명확히 알 수 있었습니다. 아래는 해당 코드입니다.
```java
public void beforeTestMethod(final TestContext testContext) throws Exception {
    Method testMethod = testContext.getTestMethod();
    Class<?> testClass = testContext.getTestClass();
    Assert.notNull(testMethod, "Test method of supplied TestContext must not be null");
    TransactionContext txContext = TransactionContextHolder.removeCurrentTransactionContext();
    Assert.state(txContext == null, "Cannot start new transaction without ending existing transaction");
    PlatformTransactionManager tm = null;
    TransactionAttribute transactionAttribute = this.attributeSource.getTransactionAttribute(testMethod, testClass);
    if (transactionAttribute != null) {
        ...
        tm = this.getTransactionManager(testContext, transactionAttribute.getQualifier());
        Assert.state(tm != null, () -> {
            return "Failed to retrieve PlatformTransactionManager for @Transactional test: " + testContext;
        });
    }
}
```

```java
public void afterTestMethod(TestContext testContext) throws Exception {
    Method testMethod = testContext.getTestMethod();
    Assert.notNull(testMethod, "The test method of the supplied TestContext must not be null");
    TransactionContext txContext = TransactionContextHolder.removeCurrentTransactionContext();
    if (txContext != null) {
        TransactionStatus transactionStatus = txContext.getTransactionStatus();

        try {
            if (transactionStatus != null && !transactionStatus.isCompleted()) {
                txContext.endTransaction();
            }
        } finally {
            this.runAfterTransactionMethods(testContext);
        }
    }
}
```

더욱이 MergeMode.REPLACE_DEFAULTS를 하면 위에 있는 DependencyInjectionTestExecutionListener도 없어져, 테스트 환경에서 사용하는 BoardJpaRepository가 null로 제대로 주입되지 않는 것도 알게 되었습니다. (그래서 스프링이 제공해주는 리스너들을 활용하기 위해서는 반드시 MERGE_WITH_DEFAULTS로 설정해야 함을 알았습니다.)

다만 공식 문서를 보면 REPLACE_DEFAULTS가 하위 호환성을 위해 기본값으로 설정되어 있다는데, 정확히 왜 그런 것인지는 잘 나와 있지가 않네요.. 

이벤트, 동기/비동기 등 아직 모르는 것이 많다고 느껴진 것 중 하나였던 것 같습니다!

2024-01-31 07:46 UTC, devholic22 commented on src/main/java/com/mju/mentoring/board/controller/BoardController.java
> +                .map(board -> new BoardSearchResponse(board.getId(), board.getTitle(), board.getContent()))
음.. 아직 `언제 정적 팩터리를 사용하고, 언제 생성자를 사용하는 게 좋을 지` 기준을 세우진 못한 것 같습니다.
다만 빌더 패턴을 사용할 시점과 비슷하게, `파라미터의 갯수가 3개 이상 정도 되면 DTO에 객체를 넘김으로써 해결`한다는 의견을 가지고 개발해보겠습니다!

2024-01-31 07:51 UTC, devholic22 commented on src/main/java/com/mju/mentoring/board/domain/Board.java
> +    public Board(final String title, final String content) {
정적 팩터리 메서드에 대해 고민을 해 본 결과, 동일한 객체를 다양한 방법으로 만들 상황이 생기거나 (ex: 특정 필드만 입력받도록 하고 나머지는 기본값으로 처리시키는 경우가 많을 때), 필드가 너무 많을 때 (3개 이상 정도) 사용하는 게 좋겠다는 생각이 들었습니다.

개인적으로는 물론 확장성을 고려하면 말씀하신 대로 boardText (title, content) 말고도 파일, 이미지 등만 올리는 경우가 있을 수 있으니 정적 팩터리 메서드를 사용할 수 있으나, 현재 단계에서는 생성자로 해도 충분할 것 같다는 생각이 듭니다..!

태인 님께서는 언제 생성자를 쓰시고 언제 정적 팩터리 메서드를 사용하시는지 여쭤봐도 될까요?

2024-02-01 02:04 UTC, devholic22 commented on src/main/java/com/mju/mentoring/board/domain/BoardText.java
> +public class BoardText {
불변인 객체더라도 EqualsAndHashcode를 재정의하지 않을 경우 논리적으로 동등한 경우에서 같지 않게 나올 수 있으며, 만약 Board에서 동등 비교를 한다면 BoardText에서 false가 일어날 수도 있으므로 재정의해야 함을 새롭게 알았습니다.

추가로 롬복의 기본 어노테이션을 활용하면 디컴파일 했을 때 모든 필드에 대해서 재정의 시켜준다는 것을 알았고, exclude 등으로 제외할 필드들을 정의할 수 있다는 것 등을 알았습니다!

2024-02-01 03:33 UTC, devholic22 commented on src/test/java/com/mju/mentoring/board/controller/BoardControllerTest.java
> +
[해당 글](https://m.blog.naver.com/qjawnswkd/222310449851)을  알게 되어 `assertInstanceOf(예외, result.getResolvedException())` 용법을 알게 되었습니다! 다만 다른 테스트들에서는 예외가 터졌을 시 error에 대한 내용이 json으로 나오는게 통과하는데, 이렇게 커스텀으로 작성한 예외들에 대해서는 실제와 다르게 메시지가 나오지 않네요.. 왜 그런지 좀 더 찾아보겠습니다!

처음 사진은 실제로 포스트맨에서의 예외 상황, 두 번째 사진은 테스트했을 때 결과입니다.
![스크린샷 2024-02-01 오후 12 31 36](https://github.com/sosow0212/2024-mju-mentoring/assets/90085154/aed2cf95-dfc5-4665-a037-e87f61aa9d10)

![스크린샷 2024-02-01 오후 12 33 14](https://github.com/sosow0212/2024-mju-mentoring/assets/90085154/d6dde5dd-4b52-4142-8f87-9401f1dc18f4)

2024-02-06 09:29 UTC, eom-tae-in requested changes
고생하셨습니다. 몇가지만 수정해주세요

2024-02-06 09:29 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/member/controller/AuthController.java
> +        Long memberId = newMember.getId();
authService.signup()에서 Member를 반환하지 말고 memberId를 반환하게 하면 더 좋을거 같아요!

2024-02-06 09:29 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/member/service/AuthService.java
> +        String password = passwordManager.encode(request.password());
개인적으로 password를 encoding 하는 로직은 도메인에서 해주는 게 더 좋을 거 같다는 생각이 드네요
현준님이 PasswordManager를 damain에 두셨는데 지금 PasswordManager 로직은 서비스에서 사용하고 있네요
PasswordManager를 application layer로 바꾸거나 encoding 관련 로직은 domain에서 진행하는 것이 좋아보입니다!
(제 생각엔 데이터베이스에 저장될 비밀번호를 암호화하는 거니까 domain에서 encoding을 해주는 것이 좋아보입니다)

2024-02-06 11:38 UTC, sosow0212 approved these changes
수고하셨습니다 pr이 계속 쌓여서 일단 여기서 한 번 끊고 가겠습니다!
세션, 쿠키, 토큰 방식으로 구현 잘 해주셨네요 멘토링 진행후에 리팩토링 하는 방향으로 가보면 좋을 것 같습니다.

2024-02-06 11:38 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/controller/AuthController.java
> +    private static final int SESSION_EXPIRE_SECONDS = 3600;
컨트롤러로 넘어오기 전에 처리할 수 있는 방법은 없을까요?

2024-02-06 11:38 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/controller/MemberController.java
> +    public ResponseEntity<ProfileResponse> profileWithCookie(final HttpServletRequest request) {
profileWithCookie 라는 네이밍은 어떤 것을 의미하는 것인가요?

2024-02-06 11:38 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/service/AuthService.java
> +        String password = passwordManager.encode(request.password());
제 생각에도 passwordManager는 인터페이스로 도메인 위치에 두고 서비스에서 구현체를 넘기는 방식으로 사용하는 것이 더 좋아보입니다.

2024-02-06 11:38 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/service/AuthService.java
> +        }
JPA에서 isExist 이렇게 할 수 있지 않을까요?

2024-02-06 11:38 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/service/AuthService.java
> +    public Member nonJwtLogin(final LoginRequest request) {
non은 무엇인가요 메서드 네이밍 신경써주세요

2024-02-06 11:38 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/service/helper/MemberServiceHelper.java
> +public class MemberServiceHelper {
이 클래스는 무슨 역할을 하나요?
굳이 뺄 필요가 있을까요? 이유가 궁금합니다.

서비스레이어에서 하는 것이랑 무엇이 다른가요?

2024-02-06 11:41 UTC, merged