S2ungho
sosow0212/2024-mju-mentoring pull request #7
Opened 2024-01-20 05:35 UTC by S2ungho

게시글 CRUD 기능 구현 완료 하였습니다

감사합니다

2024-01-20 07:13 UTC, eom-tae-in requested changes
고생하셨습니다.

2024-01-20 07:13 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/board/contorller/BoardController.java
> +        return ResponseEntity.ok().build(); //HTTP 상태토드 200 반환
한 줄에 체이닝은 하나만 적는 것이 좋습니다!
https://catsbi.oopy.io/bf003ff6-2912-4714-8ac2-44eeb7becc93

2024-01-20 07:13 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/board/repository/BoardRepository.java
> +public interface BoardRepository extends JpaRepository<Board, Long> {
JpaRespository를 상속받을 때는 @Repository를 써주지 않아도 됩니다.

2024-01-20 07:45 UTC, sosow0212 requested changes
처음이라서 미숙하신 부분이 있지만, 이는 고쳐 나가면 됩니다! 처음치고 잘하셨고 고생하셨습니다.
코멘트 달아준 부분 모두 공부하고 고치고 다시 리뷰신청해주세요!

그리고 학습 테스트도 하시고 제출하셔야합니다~

2024-01-20 07:45 UTC, sosow0212 commented on build.gradle
> +    runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'
이미 mysql 종속성이 있는데 mariaDB를 사용하신 이유가 있을까요?

2024-01-20 07:45 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/contorller/BoardController.java
> +@Controller // 컨트롤러 역할을 한다는 것을 나타냄, 클라이언트의 요청을 처리하고 응답을 반환하는 메소드를 포함하고 있음
API 멘토링인데 RestController가 아닌 Controller를 사용하신 이유가 무엇인가요?

@RestController와 @Controller의 차이점은 무엇일까요?

2024-01-20 07:45 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/contorller/BoardController.java
> +    @Autowired // 생성자 기반 의존성 주입 (Constructor-based Dependency Injection) 클래스의 불변성을 보장, 의존성이 명확하게 드러남, 테스트하기 쉬움.
의존성 주입 방식 중에서 생성자 주입을 하셨네요!
다만, 생성자가 한 개인 경우는 @Autowired를 생략하셔도 됩니다.

2024-01-20 07:45 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/contorller/BoardController.java
> +        return ResponseEntity.ok(boardService.save(board)); //게시글 저장 및 HTTP 상태코드 200과 함께 게시글 객체 반환
200 응답코드를 내려줘도 상관 없으나 자원이 생성되는 경우 201 CREATED를 주기도 합니다.

2024-01-20 07:45 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/contorller/BoardController.java
> +    public ResponseEntity<List<Board>> getAllBoards() {
만약 Response에 List<Member>를 주게 된다면 member.password도 노출될 수 있지 않을까요?

Dto를 씌워서 반환한 것과 List<Board>를 주는 것의 차이는 무엇일까요?

2024-01-20 07:45 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/contorller/BoardController.java
> +    @PutMapping("/{id}")// /board/{id} 경로로 들어오는 PUT 요청 처리 // @PathVariable을 사용하여 {id}를 인자로 전달
HTTP에서 PUT, PATCH 메서드의 차이점도 공부해보시면 좋을 것 같습니다.

2024-01-20 07:45 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/contorller/BoardController.java
> +    public ResponseEntity<Board> updateBoards(@PathVariable Long id, @RequestBody Board boardDetails) {
RequestBody 부분도 Dto로 받는 것과 순수 도메인로 받는 것은 무엇이 다를까요?

2024-01-20 07:45 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/contorller/BoardController.java
> +        return ResponseEntity.noContent().build(); //삭제요청이 성공적으로 진행되었을 떄, 콘텐츠가 없다는 상태코드 204 반환(noContent)
204, noContent 👍

항상 이렇게 주는 것이 정답은 아닙니다! 팀원과의 대화를 통해 200을 줄 수도 있고 혹은 데이터를 반환해줄 수 있다는 점도 아셨으면 좋겠습니다 :)

2024-01-20 07:45 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/contorller/BoardController.java
> +import org.springframework.web.bind.annotation.*;
구글 자바 컨벤션에서는 import 문에서 `*`과 같은 와일드카드를 지양하라고 했습니다!
추가적으로 항상 코드를 작성했으면 정렬과 불필요한 import는 제거하는 습관을 가지면 좋습니다.

정렬 단축키 : cmd + option + L
미사용 import 제거 단축키 : cmd + option + o

2024-01-20 07:45 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/domain/Board.java
> +@Getter @Setter // lombok
Lombok을 사용하셨네요.
롬복에서의 @Data는 무엇으로 이뤄져있을까요?

@Getter @Setter가 @Data안에 포함되어 있어서 나머지는 제거하셔도 됩니다.
하지만, 객체지향적으로는 @Setter를 지양하는게 좋습니다.

스프링이 익숙하지 않으시다면 롬복을 아에 사용하지 않고 코드로 작성해보는 것이 훨씬 좋을 것 같습니다

2024-01-20 07:45 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/domain/Board.java
> +@NoArgsConstructor  // 기본 생성자 생성 lombok
다른 클래스에서 Board의 기본생성자를 부를 수 있을까요? 접근제어자가 public일 것 같은데 어떻게 생각하시나요?

2024-01-20 07:45 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/repository/BoardRepository.java
> +public interface BoardRepository extends JpaRepository<Board, Long> {
JpaRepository를 까보면 안에 @Repository로 빈이 등록되어 있습니다.
따라서 @Repository를 생략하셔도 됩니다.

extends로 상속 받는 경우는 부모 클래스의 빈도 같이 받을 수 있다는 점!

2024-01-20 07:45 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +        board.setContent(boardDetails.getContent()); //content 업데이트
도메인과 서비스 레이어의 차이점은 무엇일까요?

setter를 통해서 서비스에서 도메인에 접근하여 업데이트를 진행시켜주는데  만약 setTitle을 깜빡한다면 문제가 생길 수 있지 않을까요? (휴먼 에러)

따라서 도메인에 update 메서드를 만들고 서비스에서는 도메인의 메서드만 호출하는 방식으로 코드를 작성하는 것이 좋습니다.
`객체지향의 사실과 오해` 책을 읽어보시면 도움 되실 것 같아요.

그리고 @Transactional 어노테이션이 메서드 상단에 붙으면 JPA의 더티체킹으로 인해서 `repository.save(...)`를 사용하지 않아도 자동으로 변경사항이 저장이 됩니다.

다른 부분에도 @Transactional 어노테이션이 없는데 이 어노테이션의 역할은 무엇이고, JPA에서 해당 어노테이션이 붙으면 어떻게 작동이 되는지 공부해보셔야할 것 같습니다.

2024-01-20 07:45 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +
불필요한 개행이 있습니다

2024-01-21 16:26 UTC, S2ungho commented
- Dto를 씌워서 반환한 것과 List를 주는 것의 차이 : 
Dto를 씌워서 반환: 엔티티의 모든 정보를 노출하지 않고 필요한 정보만 클라이언트에 전달할 수 있음. 민감한 정보를 숨기는 데 유용.
List 반환: 엔티티의 모든 정보를 그대로 노출할 위험이 있음.

- RequestBody 부분도 Dto로 받는 것과 순수 도메인로 받는 것의 차이 : 
DTO로 받기: 클라이언트로부터 필요한 데이터만을 안전하게 받을 수 있음.
도메인으로 받기: 민감한 정보 노출 될 수 있음. 엔티티가 클라이언트에 의해 직접적으로 변경될 수 있음.

- PUT과 MATCH 메서드의 차이 : 
PUT: 전체 업데이트를 위해 사용됨.
PATCH: 부분적인 업데이트를 위해 사용됨.

- 도메인과 서비스 레이어의 차이 : 
setter를 통해서 서비스에서 도메인에 접근하여 업데이트를 진행시켜주는데 만약 setTitle을 깜빡한다면 문제가 생길 수 있지 않을까요? (휴먼 에러)  -> 도메인 로직 캡슐화 : 도메인에 update 메서드를 만들고 서비스에서 호출

- @Transactional 어노테이션 : 데이터베이스 작업을 수행하고 트랜잭션 관리를 해야할 때, 주로 서비스 클래스나 리포지토리 클래스와 같은 데이터 액세스 계층에서 사용

-> DTO 를 사용하는 것과 LIST자체로 주는 것이 보안상 취약할 수 있다는 점을 알게되었고, 의존성 주입과 @Autowired 및 생성자 기반 주입 방식에 대해 이해할 수 있었습니다.

2024-01-22 12:06 UTC, eom-tae-in requested changes
고생하셨습니다. 몇 가지만 수정해 주세요~

2024-01-22 12:06 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +        board.setContent(boardDto.getContent()); // boardDto의 내용을 가져와서 board에 설정
setter를 통해 값을 변경하면 값의 변경 의도를 파악하기 어렵기 때문에 다음과 같이 값을 세팅하는 것은 좋지 않습니다~
객체를 생성하는 시점에 필드의 값을 세팅하도록 필드들을 매개변수로 가지는 생성자를 만들어서 사용해주세요

2024-01-22 12:06 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +    public List<BoardDto> findAll() {
데이터 조회를 할 때도 데이터의 일관성과 격리를 위해 @Transcational을 사용해야합니다. 
읽기 전용 트랜잭션 @Transactional(readOnly = true)를 붙여주세요.

2024-01-22 12:06 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/board/domain/Board.java
> +@Data // lombok - 컨틀롤러의 board.get 이용 //@Data에 @Getter @Setter가 포함되어 있음.
Data 어노테이션을 사용하게 되면 무분별하게 Setter를 남용하게 됩니다. Data 어노테이션을 사용하지 않도록 리팩터링 해보면 좋을 것 같아요!

2024-01-22 12:06 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/board/dto/BoardDto.java
> +}
클래스 파일 마지막 줄에 개행 추가해주세요~

https://seongwon.dev/Git/20220303-%ED%8C%8C%EC%9D%BC%EC%9D%98_%EB%A7%88%EC%A7%80%EB%A7%89_%EA%B0%9C%ED%96%89/

2024-01-22 12:06 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/board/repository/BoardRepository.java
> +@Transactional
Repository에 @Transcational을 붙이신 이유가 있나요?

Service에서 레포지토리의 메소드를 호출하기 때문에 @Transactioanl 어노테이션을 Service Layer에만 작성하시면 됩니다 :)

2024-01-26 19:43 UTC, S2ungho commented
2주차 과제 제출합니다!
테스트 코드 관련해서 참고할만한 래퍼런스가 있을까요?? 어디부터 어떻게 해야할지 모르겠네요 ㅠㅠ

2024-01-27 05:12 UTC, sosow0212 requested changes
주석부터 엄청 공부 열심히 하신게 느껴집니다!

리뷰에 질문 남긴거 확인해보시고 코멘트로 답변 부탁드립니다!
++ 테스트는 작성하지 않으신 이유가 있을까요??

2024-01-27 05:12 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/controller/BoardController.java
> +                .build(); //삭제요청이 성공적으로 진행되었을 떄, 콘텐츠가 없다는 상태코드 204 반환(noContent)
와 진짜 주석이랑 학습 열정에 박수치고 갑니다 대단하십니다 👍

2024-01-27 05:12 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/domain/Board.java
> +import jakarta.persistence.*;
import에 와일드카드는 지양해주세요!

`인텔리제이 import 와일드카드` 키워드로 검색해서 설정해주시고 왜 지양해야하는지는 블로거의 생각이 아닌 본인의 생각을 댓글로 의견 공유 부탁드릴게요.

맥북을 사용한다면 인텔리제이에서 shift 두번 누르고 검색어로 `.*;` 검색하셔서 모두 바꾸시면 됩니다 ㅎㅎ

2024-01-27 05:12 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/domain/Board.java
> +        this.boardContent.update(title, content);
👍

2024-01-27 05:12 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/domain/BoardContent.java
> +public class BoardContent {
`@Embeddable` 어노테이션이 없다면 작동하지 않을 것 같네요!

Embedded와 Embeddable의 차이점과 왜 사용하는지 공부해보면 좋을 것 같습니다

2024-01-27 05:12 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/domain/BoardContent.java
> +    }
setter가 있네요!

객체지향에서 정말 가급적이면 setter를 지양하는게 좋습니다.
왜 그럴까요?

2024-01-27 05:12 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/dto/BoardDto.java
> +    private Long id;
1. 한칸 개행 추가해주세요!

2. 클래스 네이밍이 `BoardDto`인데 어떤 dto인지 명확하지 않습니다. `BoardCreateRequest` or `BoardResponse`와 같은 네이밍이 더 좋을 것 같습니다.

3. 롬복 라이브러리의 @Data 어노테이션은 무엇으로 이뤄져있을까요?
그리고 @Data와 @AllArgs~ 가 없다면 해당 클래스는 어떻게 구현해야할까요?

4. 우리는 자바17을 사용하고 있습니다. 위에 질문 모두 답변 후에 `record 클래스`를 공부해본 후 적용하시면 좋을 것 같습니다!

2024-01-27 05:12 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +        return new BoardDto(savedBoard.getId(), savedBoard.getBoardContent().getTitle(), savedBoard.getBoardContent().getContent()); // BoardDto 생성
save를 한 후에 Board를 주는 경우도 있고 Id를 주는 경우도 있고 void를 반환하는 경우도 있습니다.

정답은 없지만 각자 어느 상황에서 사용될까요? 
프론트엔드와의 협업 측면에서 생각해보고 답변해주세요!

2024-01-27 05:12 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +                .map(board -> new BoardDto(board.getId(), board.getBoardContent().getTitle(), board.getBoardContent().getTitle())) //Board에서 각각 BoardDto로 변환
`new BoardDto(board.getId(), board.getBoardContent().getTitle(), board.getBoardContent().getTitle())`

--> 정적 팩토리 메서드를 사용해보시면 좋을 것 같습니다

1. 정적 팩토리는 무엇인가요?
2. 정적 팩토리를 사용했을 때 장점은 무엇인가요?
3. 정적 팩토리 메서드 사용시 주의해야할 점은 무엇인가요?

공부한 후에 본인의 생각 적어주시면 좋을 것 같습니다!

2024-01-27 05:12 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +                .orElseThrow(() -> new EntityNotFoundException("게시글을 찾을 수 없습니다. - " + id)); //게시글을 찾을 수 없는 경우 EntityNotFoundException 발생
CustomException을 만들어주셨네요.

해당 클래스를 사용할 때 `"게시글을 찾을 수 없습니다. - "` 이 문구를 사용할 때마다 적어줘야할 것 같은데
디버깅을 위한 id값만을 넘기면 알아서 위에 문구를 추가해주기 위해선 어떻게 해야할까요?

2024-01-27 05:33 UTC, eom-tae-in requested changes
고생하셨습니다. 몇 가지만 수정해 주세요~

2024-01-27 05:33 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/exam/number_pojo/TestNumberGenerator.java
> +public class TestNumberGenerator implements NumberGenerator{
개행 추가해주세요~

2024-01-27 05:33 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/board/controller/BoardController.java
> +    public ResponseEntity<BoardDto> createBoard(@RequestBody BoardDto boardDto) {
create와 update에서 같은 BoardDto를 사용하고 있는데 이걸 CreateRequest와 UpdateRequest로 나눠보는 건 어떨까요?
BoardDto라는 클래스 네이밍으로는 어떤 Dto의 역할인지 알기 어려울 거 같아요!

2024-01-27 09:04 UTC, S2ungho commented on src/main/java/com/mju/mentoring/board/controller/BoardController.java
> +                .build(); //삭제요청이 성공적으로 진행되었을 떄, 콘텐츠가 없다는 상태코드 204 반환(noContent)
감사합니다! 교수님께서 주석 습관들이라고 하기도 하셨구 자꾸 잊어버려서 적어놓으면 도움이 많이 되네요!

2024-01-27 09:06 UTC, S2ungho commented on src/main/java/com/mju/mentoring/board/domain/Board.java
> +import jakarta.persistence.*;
import된 jakarta.persistence를 모두 불러오게되면 사용하지 않는 것들이 더 많아 자원을 낭비하게 된다는 저의 생각입니다!
자동으로 import 추가 되는 option+enter 단축키 사용하다보니깐 추가가 된 것 같네요! 지양하도록 하겠습니다!

2024-01-27 09:19 UTC, S2ungho commented on src/main/java/com/mju/mentoring/board/domain/BoardContent.java
> +public class BoardContent {
- @Embaddable과 @Embedded의 차이점

[@Embaddable]
BoardContent 의 @Embeddable 어노테이션은 BoardContent 클래스가 다른 엔티티에 포함될 수 있다는 것을 나타냅니다. 또한 Board 클래스(엔티티)의 일부분으로만 사용됩니다.

[@Embedded]
board의 @Embedded 어노테이션은 엔티티 내에서 @Embeddable로 정의된 BoardContent 클래스의 인스턴스를 포함시킵니다.

2024-01-27 09:26 UTC, S2ungho commented on src/main/java/com/mju/mentoring/exam/number_pojo/TestNumberGenerator.java
> +public class TestNumberGenerator implements NumberGenerator{
추가하였습니다! 구글 자바 컨벤션에 따라 습관 들이고, 개행 추가하는 것들 주의 하겠습니다!

2024-01-27 09:36 UTC, S2ungho commented on src/main/java/com/mju/mentoring/board/domain/BoardContent.java
> +    }
- 세터를 통해 객체의 상태를 변경하면 세터들의 호출 순서에 따라 객체 상태가 달라져 버그를 발생시킬 수 있기 때문입니다.
- 세터 메소드 호출을 깜빡하여 필드의 일부는 초기화 되지 않은 상태로 남아있을 수 있기 때문입니다.

2024-01-27 09:40 UTC, S2ungho commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +        return new BoardDto(savedBoard.getId(), savedBoard.getBoardContent().getTitle(), savedBoard.getBoardContent().getContent()); // BoardDto 생성
Board를 반환하는 경우 - 프론트엔드에서 저장된 데이터를 즉시 다시 사용해야할 때
ID를 반환하는 경우 - 프론트엔드에서 저장된 객체의 정보를 식별해야할 때
void 를 반환하는 경우 - 저장이 되었는지 안되었는지만 알면 될 때

위와 같은 프론트엔드의 각 상황에 따라 다를 것 같습니다.

2024-01-28 09:36 UTC, S2ungho commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +                .orElseThrow(() -> new EntityNotFoundException("게시글을 찾을 수 없습니다. - " + id)); //게시글을 찾을 수 없는 경우 EntityNotFoundException 발생
- 예외를 던질 때, "게시글을 찾을 수 없습니다. - " + id 의 예외 메시지를 매번 직접 작성해야 하므로, 코드 중복과 유지 보수가 복잡해짐.

- "게시글을 찾을 수 없습니다. - " + id 의 예외 메시지를 자동으로 생성하는 CustomException 클래스를 생성하여 코드의 중복을 줄이고, 유지 보수성 향상.

2024-01-28 12:32 UTC, S2ungho commented on src/main/java/com/mju/mentoring/board/service/BoardService.java
> +                .map(board -> new BoardDto(board.getId(), board.getBoardContent().getTitle(), board.getBoardContent().getTitle())) //Board에서 각각 BoardDto로 변환
1. 정적 팩토리는 무엇인가요?
- new 키워드를 사용하여 직접 객체를 생성하는 대신, 클래스 내에 정의된 정적 메서드를 호출하여 객체의 인스턴스를 반환받음
2. 정적 팩토리를 사용했을 때 장점은 무엇인가요?
- 호출할 때마다 새로운 객체를 생성하지 않아도 됨
3. 정적 팩토리 메서드 사용 시 주의해야할 점은 무엇인가요?
- 정적 메서드는 상속되지 않으므로, 하위 클래스에서 이를 오버라이드할 수 없음

-> 정적 팩토리를 공부한 후 
객체 생성 방식을 new 키워드를 사용하는 대신, 클래스 내에 정의된 정적 메서드를 통해 인스턴스를 반환하는 방식을 사용하며 객체 생성 과정을 더 유연하게 관리할 수 있었고, 코드의 의도를 더 명확히 전달할 수 있었습니다.

호출할 때마다 새로운 객체를 생성하지 않고, 메모리 사용을 최소화 하며, 코드의 가독성과 유지 보수성을 향상시킨다는 것을 알게 되었습니다.

하지만 상속이 되지 않기 때문에 상속이 필요할 때를 고려하여 적절한 상황에서 사용하는 것이 중요할 것이라는 생각을 하게 되었습니다.

2024-01-28 15:36 UTC, S2ungho commented on src/main/java/com/mju/mentoring/board/dto/BoardDto.java
> +    private Long id;
1. 한칸 개행 추가해주세요!
- 추가 완료 하였습니다. -> 구글 자바 컨벤션에 따라 습관 들이고, 개행 추가하는 것들 주의 하겠습니다!

2.클래스 네이밍이 BoardDto인데 어떤 dto인지 명확하지 않습니다. BoardCreateRequest or BoardResponse와 같은 네이밍이 더 좋을 것 같습니다.
- 



3. 롬복 라이브러리의 @DaTa 어노테이션은 무엇으로 이뤄져있을까요?
- 모든 필드에 대한 Getter 메서드, Setter 메서드 자동 생성, 클래스의 필드를 포함하는 toString 메서드를 자동 생성
- 객체의 동등성 비교를 위한 equals와 hashCode 메서드를 필드를 기반으로 자동 생성

3-1 그리고 @DaTa와 @AllArgs~ 가 없다면 해당 클래스는 어떻게 구현해야할까요?
- @AllArgsConstructor 어노테이션은 생성자를 자동으로 생성해줌
- [1] getter와 setter 메서드, 
- [2] 그리고 toString, equals, hashCode 메서드, 
- [3] 모든 필드를 매개변수로 받는 생성자도 직접 작성해야함
- Lombok을 사용하지 않고 수동으로 클래스를 구현하면, 코드 양이 많아지고 유지 보수가 더 복잡해질 수 있음
- 하지만, Lombok의 사용이 어려운 환경이거나, Lombok에 대한 의존성을 줄이고 싶은 경우에는 이와 같이 수동으로 구현

4. 우리는 자바17을 사용하고 있습니다. 위에 질문 모두 답변 후에 record 클래스를 공부해본 후 적용하시면 좋을 것 같습니다!
- record 클래스는 데이터 운반 객체의 간결한 표현을 가능하게 함
- 각 필드에 대한 getter 메서드, equals(), hashCode(), toString() 메서드를 자동으로 생성
- Long id, String title, String content 필드에 대한 getter 메서드, equals(), hashCode(), toString() 메서드가 자동으로 생성
- lombok의 AllArgsConstructor, Data 대신 record를 사용

2024-01-30 06:52 UTC, S2ungho commented on src/main/java/com/mju/mentoring/board/controller/BoardController.java
> +    public ResponseEntity<BoardDto> createBoard(@RequestBody BoardDto boardDto) {
**- create와 update에서 같은 BoardDto를 사용하고 있는데 이걸 CreateRequest와 UpdateRequest로 나눠보는 건 어떨까요?
BoardDto라는 클래스 네이밍으로는 어떤 Dto의 역할인지 알기 어려울 거 같아요!**

(1) BoardCreateRequest : 게시글 생성 요청시 사용
(2) BoardUpdateRequest : 게시글 수정 요청시 사용
(3) BoardResponse : 게시글의 상세 정보 응답시 사용
(4) BoardListResponse : 게시글 목록 조회 응답시 사용

2024-02-05 13:44 UTC, S2ungho commented
3주차 과제 제출합니다
테스트 코드는 작성하고 있는데 많이 부족한 것 같아 조금 더 찾아보고 마무리 해보겠습니다

2024-02-06 05:38 UTC, eom-tae-in requested changes
승호 님께서 제출해 주신 과제에 테스트가 없는데 pr 날리실 때 테스트가 누락되었는지 한번 확인해 주세요
그리고 리뷰해 드린 내용 확인하시고 수정해 주세요~

2024-02-06 05:38 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/board/domain/BoardContent.java
> +
마지막 개행 삭제해주시고  불필요한 Setter 메서드도 삭제해주세요~

2024-02-06 05:38 UTC, eom-tae-in commented on src/main/java/com/mju/mentoring/member/controller/MemberController.java
> +    }
- @RequestBody로 Member를 넘겨 받는 것은 좋지 않아보입니다. dto를 이용하도록 변경해주세요.
- member.isPresent()는 ui 계층에 있기엔 부적절한 메서드입니다. 차라리 memberService에서 memberRepository.findByUsernameAndPassword(username, password)를 한 뒤에 member가 존재하는지 검증을 한 뒤 Member 타입으로 반환을 하는 것이 좋아보입니다.
- 그리고 회원가입 기능은 구현을 안하신거 같은데 회원가입 기능이 없다면 로그인을 할 수 있을까요?

2024-02-06 11:47 UTC, sosow0212 approved these changes
수고하셨습니다!
pr이 길어져서 일단 한 번 끊고 가겠습니다.

테스트가 많이 누락되어 있고 아직은 계층 이해와 조금 부족한 부분이 있는데 이런 부분은 차차 개선해나가면 될 것 같습니다. 어려웠을텐데 수고하셨습니다!

2024-02-06 11:47 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/board/controller/BoardController.java
> +                .build(); //삭제요청이 성공적으로 진행되었을 떄, 콘텐츠가 없다는 상태코드 204 반환(noContent)
하지만 너무 많은 주석은 오히려 불필요하게 가독성을 저해시킬 수 있기 때문에 나중에 협업할 때에는 코드를 한 번에 보기 힘든 경우(이런 경우도 피해야하지만)에 달아주는게 좋습니다!

2024-02-06 11:47 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/member/service/MemberService.java
> +        return memberRepository.findByUsernameAndPassword(username, password); // 인증에 성공하면 해당 멤버, 실패하면 빈 Optional을 반환
찾지 못한다면 예외를 발생해줘야하지 않을까요?
현재 레이어에서 예외를 발생시키고, 유저 정보가 있다면, ui단에서는 유저에 대한 정보가 있다고 쿠키에 설정을 해주든 해야할 것 같습니다

2024-02-06 11:48 UTC, merged

2024-02-06 13:08 UTC, s5oham commented on src/main/java/com/mju/mentoring/board/domain/BoardContent.java
> +
확인했습니다!

2024-02-06 13:11 UTC, S2ungho commented on src/main/java/com/mju/mentoring/member/controller/MemberController.java
> +    }
넵 엔티티가 직접적으로 노출되지 않게 DTO를 이용하겠습니다!
계층에 대한 이해를 조금 더 해보도록 하겠습니다!
회원가입 기능도 구현해볼게요!
감사합니다 :)