Zoid79
sosow0212/2024-mju-mentoring pull request #9
Opened 2024-01-25 06:20 UTC by zoid79

최대한 메소드 별로 테스트 코드를 작성하려고 하였습니다.
또한 Member 도메인도 객체 지향적으로 바꾸었습니다

2024-01-25 08:24 UTC, sosow0212 requested changes
전반적으로 실습 코드랑 너무 비슷해서 질문식으로 리뷰를 남겼습니다
확인하고 코멘트로 답글 부탁드리고 수정해주세요!

2024-01-25 08:24 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/controller/dto/BoardResponse.java
> +public class BoardResponse {
어느정도 이해하신 것 같은데 이제 자바17을 쓰니 record 클래스를 사용해서 dto를 만들어보는 것은 어떨까요?

2024-01-25 08:24 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/domain/MemberDescription.java
> +    @Column(nullable = false)
username으로 회원가입의 id를 쓰는 것 같은데 그렇다면 현재 구조로는 동일한 username으로 회원가입이 가능할 것 같네요

2024-01-25 08:24 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/infrastructure/BoardRepositoryImpl.java
> +}
저번에 리뷰 남겼는데 아직도 No newline at a end of file가 발생하네요 설정 부탁드립니다

2024-01-25 08:24 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/service/BoardService.java
> +    public Board findByIdOrThrowException(Long id) {
1. 개행 추가해주세요
2. 접근제어자를 public으로 한 이유가 무엇인가요?

2024-01-25 08:24 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/service/dto/BoardCreateRequest.java
> +@AllArgsConstructor
RequestDto에서 전체 필드를 받는 생성자가 필요할까요?
스프링에서 직렬화, 역직렬화 공부를 해보시면 좋을 것 같아요

2024-01-25 08:24 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/service/dto/BoardCreateRequest.java
> +@AllArgsConstructor
+ 코멘트로 위에 리뷰에 대한 답변 부탁드립니다!

그리고 답변 후에 record 클래스로 변경하시면 됩니다.

2024-01-25 08:24 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/controller/BoardControllerWebMvcTest.java
> +    @MockBean
Autowired와 MockBean의 차이점은 무엇인가요?

2024-01-25 08:24 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/controller/BoardControllerWebMvcTest.java
> +        when(boardService.save(eq(req))).thenReturn(savedBoard.getId());
when()을 사용하면 어떤 일이 발생하나요?

2024-01-25 08:24 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/controller/BoardControllerWebMvcTest.java
> +                .andExpect(status().isOk());
현재 해당 메서드에서 검증은 어떤 것만 하고 컨트롤러라면 어떤 검증이 더 필요할까요?

2024-01-25 08:24 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/controller/BoardControllerWebMvcTest.java
> +                .andExpect(status().isOk());
이 부분이 있는 이유가 무엇인지 궁금합니다!

2024-01-25 08:24 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/controller/BoardControllerWebMvcTest.java
> +
불필요한 공백이 있습니다

2024-01-25 08:24 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/controller/BoardControllerWebMvcTest.java
> +                .contentType(MediaType.APPLICATION_JSON)
제거시에 반환하는 것이 없는데 contentType이 있는 이유가 무엇일까요?
`contentType`은 무엇을 하나요?

2024-01-25 08:24 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardFakeRepository.java
> +
불필요한 개행

2024-01-25 08:24 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardFakeRepository.java
> +public class BoardFakeRepository implements BoardRepository {
FakeRepository를 사용하는 이유는 무엇인가요?

2024-01-25 08:24 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardFakeRepository.java
> +                .map(map::get);
수업 때 같이해서 그대로 적으신 것 같은데, `map::get`을 하면 예외가 발생할 수 있지 않을까요?
어떻게 반환을 해줘야할지 고민해보시고 리팩토링하면 좋을 것 같습니다.

keyword
1. Optional
2. Stream

2024-01-25 08:24 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +                    .ignoringFields("id")
이 두 부분의 역할은 무엇인가요?

2024-01-25 08:24 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +                    .ignoringFields("id");
현재 게시글을 3개 생성하는데 한 개만 검증해도 될까요?

2024-01-25 08:24 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +    void 게시글을_삭제한다() {
이 부분에는 given-when-then 주석이 빠져있네요~

2024-01-25 08:24 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +        assertThat(foundBoards.size()==0);
이러면 검증이 되나요!?

```suggestion
        assertThat(foundBoards).hasSize(0);
```

2024-01-25 08:24 UTC, sosow0212 commented on src/test/java/com/mju/mentoring/board/service/BoardServiceTest.java
> +                .isInstanceOf(BoardNotFoundException.class);
`assertThatThrownBy`의 역할은 무엇인가요?

또한 체이닝으로 여러가지를 사용할 수 있는데 메시지를 검증하고 싶다면 어떤 체이닝 메서드를 사용해야하나요?

2024-01-26 06:53 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/controller/dto/BoardResponse.java
> +public class BoardResponse {
자바 17에 대한 이해도가 떨어져서 record가 있다는 정도만 알았는데 한번 학습해 보겠습니다.

2024-01-26 06:53 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/domain/MemberDescription.java
> +    @Column(nullable = false)
userid가 아닌 username이라 이름이 겹칠 수도 있다고 생각은 하였는데 
unique=true 제약조건 추가하였습니

2024-01-26 06:53 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/infrastructure/BoardRepositoryImpl.java
> +}
설정 변경을 했는데도 이러네요 
![스크린샷 2024-01-26 145825](https://github.com/sosow0212/2024-mju-mentoring/assets/87366543/1ff24df4-527c-434c-a433-d7ef46921e4a)

2024-01-26 06:53 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/service/BoardService.java
> +    public Board findByIdOrThrowException(Long id) {
delete의 경우에는 controller에서 호출하는 함수라서 public이고 findByIdOrThrowException는 자동으로 생길 때 public으로 생성된걸 수정 없이 올렸는데 private로 수정하였습니다

2024-01-26 06:53 UTC, zoid79 commented on src/main/java/com/mju/mentoring/exam/board/service/dto/BoardCreateRequest.java
> +@AllArgsConstructor
확장이 어떻게 되는지에 따라 MSA의 형태가 되어 다른 service에 요청을 보내는 request가 생기는 경우가 아니라면 해당 프로그램 내에서 request를 생성하는 경우는 없을 것 같아 필요 없을 것으로 생각됩니다.
저 같은 경우에는 테스트 코드에서 검증할 때 썼는데 builder로 대체하도록 하겠습니다

serialize, deserialize의 경우에는 외부와 데이터를 교환할 때 프로그램 바깥에서도 데이터를 전송할 수 있도록 객체와 같은 형태의 데이터를 바이트 화 하고 다시 바이트를 데이터화 하는 것으로 알 고 있습니다

record 클래스로 변경하였습니다

2024-01-26 06:53 UTC, zoid79 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +                    .ignoringFields("id")
윗 줄은 해당 함수를 호출하면서 객체 안에 있는 변수들을 하나하나 get을 사용하지 않아도 비교하는 함수이며 
아랫 줄의 함수는 id라는 field를 제외하며 위와 같은 비교를 진행하는 것으로 알고 있습니다

2024-01-26 06:53 UTC, zoid79 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +                    .ignoringFields("id");
수정하였습니다

2024-01-26 06:53 UTC, zoid79 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +    void 게시글을_삭제한다() {
수정했습니다

2024-01-26 06:53 UTC, zoid79 commented on src/test/java/com/mju/mentoring/board/infrastructure/BoardJpaRepositoryTest.java
> +        assertThat(foundBoards.size()==0);
이전 코드로 하니 어떤 것을 하더라도 통과가 됐었네요 
수정했습니다

2024-01-26 06:54 UTC, zoid79 commented on src/test/java/com/mju/mentoring/board/service/BoardServiceTest.java
> +                .isInstanceOf(BoardNotFoundException.class);
assertThatThrownBy는 예외가 발생하는지를 검증하는 코드 입니다
메시지를 검증하고 싶다면 기본적으로는 hasMessage 를 사용하고 특정 단어가 들어가 있는지 등을 알고 싶다면 containing을 붙이는 등 다양하게 message를 검증할 수 있습니다

2024-01-26 07:47 UTC, sosow0212 commented on src/main/java/com/mju/mentoring/exam/board/service/dto/BoardCreateRequest.java
> +@AllArgsConstructor
좋습니다!

2024-01-26 07:50 UTC, sosow0212 approved these changes
수고하셨습니다!
질문에 대한 답변도 잘해주셔서 Approve 하겠습니다.
어려우셨을텐데 고생 많으셨습니다

2024-01-26 07:50 UTC, merged